//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// These .proto interfaces are private and stable.
// Please see http://wiki.apache.org/hadoop/Compatibility
// for what changes are allowed for a *stable* .proto interface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: GenericRefreshProtocol.proto

package hadoop_common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
//
//	Refresh request.
type GenericRefreshRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *string                `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericRefreshRequestProto) Reset() {
	*x = GenericRefreshRequestProto{}
	mi := &file_GenericRefreshProtocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericRefreshRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericRefreshRequestProto) ProtoMessage() {}

func (x *GenericRefreshRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_GenericRefreshProtocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericRefreshRequestProto.ProtoReflect.Descriptor instead.
func (*GenericRefreshRequestProto) Descriptor() ([]byte, []int) {
	return file_GenericRefreshProtocol_proto_rawDescGZIP(), []int{0}
}

func (x *GenericRefreshRequestProto) GetIdentifier() string {
	if x != nil && x.Identifier != nil {
		return *x.Identifier
	}
	return ""
}

func (x *GenericRefreshRequestProto) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

// *
// A single response from a refresh handler.
type GenericRefreshResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitStatus    *int32                 `protobuf:"varint,1,opt,name=exitStatus" json:"exitStatus,omitempty"`  // unix exit status to return
	UserMessage   *string                `protobuf:"bytes,2,opt,name=userMessage" json:"userMessage,omitempty"` // to be displayed to the user
	SenderName    *string                `protobuf:"bytes,3,opt,name=senderName" json:"senderName,omitempty"`   // which handler sent this message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericRefreshResponseProto) Reset() {
	*x = GenericRefreshResponseProto{}
	mi := &file_GenericRefreshProtocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericRefreshResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericRefreshResponseProto) ProtoMessage() {}

func (x *GenericRefreshResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_GenericRefreshProtocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericRefreshResponseProto.ProtoReflect.Descriptor instead.
func (*GenericRefreshResponseProto) Descriptor() ([]byte, []int) {
	return file_GenericRefreshProtocol_proto_rawDescGZIP(), []int{1}
}

func (x *GenericRefreshResponseProto) GetExitStatus() int32 {
	if x != nil && x.ExitStatus != nil {
		return *x.ExitStatus
	}
	return 0
}

func (x *GenericRefreshResponseProto) GetUserMessage() string {
	if x != nil && x.UserMessage != nil {
		return *x.UserMessage
	}
	return ""
}

func (x *GenericRefreshResponseProto) GetSenderName() string {
	if x != nil && x.SenderName != nil {
		return *x.SenderName
	}
	return ""
}

// *
// Collection of responses from zero or more handlers.
type GenericRefreshResponseCollectionProto struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Responses     []*GenericRefreshResponseProto `protobuf:"bytes,1,rep,name=responses" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericRefreshResponseCollectionProto) Reset() {
	*x = GenericRefreshResponseCollectionProto{}
	mi := &file_GenericRefreshProtocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericRefreshResponseCollectionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericRefreshResponseCollectionProto) ProtoMessage() {}

func (x *GenericRefreshResponseCollectionProto) ProtoReflect() protoreflect.Message {
	mi := &file_GenericRefreshProtocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericRefreshResponseCollectionProto.ProtoReflect.Descriptor instead.
func (*GenericRefreshResponseCollectionProto) Descriptor() ([]byte, []int) {
	return file_GenericRefreshProtocol_proto_rawDescGZIP(), []int{2}
}

func (x *GenericRefreshResponseCollectionProto) GetResponses() []*GenericRefreshResponseProto {
	if x != nil {
		return x.Responses
	}
	return nil
}

var File_GenericRefreshProtocol_proto protoreflect.FileDescriptor

const file_GenericRefreshProtocol_proto_rawDesc = "" +
	"\n" +
	"\x1cGenericRefreshProtocol.proto\x12\rhadoop.common\"P\n" +
	"\x1aGenericRefreshRequestProto\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"\x7f\n" +
	"\x1bGenericRefreshResponseProto\x12\x1e\n" +
	"\n" +
	"exitStatus\x18\x01 \x01(\x05R\n" +
	"exitStatus\x12 \n" +
	"\vuserMessage\x18\x02 \x01(\tR\vuserMessage\x12\x1e\n" +
	"\n" +
	"senderName\x18\x03 \x01(\tR\n" +
	"senderName\"q\n" +
	"%GenericRefreshResponseCollectionProto\x12H\n" +
	"\tresponses\x18\x01 \x03(\v2*.hadoop.common.GenericRefreshResponseProtoR\tresponses2\x8b\x01\n" +
	"\x1dGenericRefreshProtocolService\x12j\n" +
	"\arefresh\x12).hadoop.common.GenericRefreshRequestProto\x1a4.hadoop.common.GenericRefreshResponseCollectionProtoB\x7f\n" +
	"\x1borg.apache.hadoop.ipc.protoB\x1cGenericRefreshProtocolProtosZ<github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_common\x88\x01\x01\xa0\x01\x01"

var (
	file_GenericRefreshProtocol_proto_rawDescOnce sync.Once
	file_GenericRefreshProtocol_proto_rawDescData []byte
)

func file_GenericRefreshProtocol_proto_rawDescGZIP() []byte {
	file_GenericRefreshProtocol_proto_rawDescOnce.Do(func() {
		file_GenericRefreshProtocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GenericRefreshProtocol_proto_rawDesc), len(file_GenericRefreshProtocol_proto_rawDesc)))
	})
	return file_GenericRefreshProtocol_proto_rawDescData
}

var file_GenericRefreshProtocol_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_GenericRefreshProtocol_proto_goTypes = []any{
	(*GenericRefreshRequestProto)(nil),            // 0: hadoop.common.GenericRefreshRequestProto
	(*GenericRefreshResponseProto)(nil),           // 1: hadoop.common.GenericRefreshResponseProto
	(*GenericRefreshResponseCollectionProto)(nil), // 2: hadoop.common.GenericRefreshResponseCollectionProto
}
var file_GenericRefreshProtocol_proto_depIdxs = []int32{
	1, // 0: hadoop.common.GenericRefreshResponseCollectionProto.responses:type_name -> hadoop.common.GenericRefreshResponseProto
	0, // 1: hadoop.common.GenericRefreshProtocolService.refresh:input_type -> hadoop.common.GenericRefreshRequestProto
	2, // 2: hadoop.common.GenericRefreshProtocolService.refresh:output_type -> hadoop.common.GenericRefreshResponseCollectionProto
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_GenericRefreshProtocol_proto_init() }
func file_GenericRefreshProtocol_proto_init() {
	if File_GenericRefreshProtocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GenericRefreshProtocol_proto_rawDesc), len(file_GenericRefreshProtocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_GenericRefreshProtocol_proto_goTypes,
		DependencyIndexes: file_GenericRefreshProtocol_proto_depIdxs,
		MessageInfos:      file_GenericRefreshProtocol_proto_msgTypes,
	}.Build()
	File_GenericRefreshProtocol_proto = out.File
	file_GenericRefreshProtocol_proto_goTypes = nil
	file_GenericRefreshProtocol_proto_depIdxs = nil
}
