//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// These .proto interfaces are private and stable.
// Please see http://wiki.apache.org/hadoop/Compatibility
// for what changes are allowed for a *stable* .proto interface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: GetUserMappingsProtocol.proto

package hadoop_common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
//
//	Get groups for user request.
type GetGroupsForUserRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *string                `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsForUserRequestProto) Reset() {
	*x = GetGroupsForUserRequestProto{}
	mi := &file_GetUserMappingsProtocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsForUserRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsForUserRequestProto) ProtoMessage() {}

func (x *GetGroupsForUserRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_GetUserMappingsProtocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsForUserRequestProto.ProtoReflect.Descriptor instead.
func (*GetGroupsForUserRequestProto) Descriptor() ([]byte, []int) {
	return file_GetUserMappingsProtocol_proto_rawDescGZIP(), []int{0}
}

func (x *GetGroupsForUserRequestProto) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

// *
// Response for get groups.
type GetGroupsForUserResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []string               `protobuf:"bytes,1,rep,name=groups" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsForUserResponseProto) Reset() {
	*x = GetGroupsForUserResponseProto{}
	mi := &file_GetUserMappingsProtocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsForUserResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsForUserResponseProto) ProtoMessage() {}

func (x *GetGroupsForUserResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_GetUserMappingsProtocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsForUserResponseProto.ProtoReflect.Descriptor instead.
func (*GetGroupsForUserResponseProto) Descriptor() ([]byte, []int) {
	return file_GetUserMappingsProtocol_proto_rawDescGZIP(), []int{1}
}

func (x *GetGroupsForUserResponseProto) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

var File_GetUserMappingsProtocol_proto protoreflect.FileDescriptor

const file_GetUserMappingsProtocol_proto_rawDesc = "" +
	"\n" +
	"\x1dGetUserMappingsProtocol.proto\x12\rhadoop.common\"2\n" +
	"\x1cGetGroupsForUserRequestProto\x12\x12\n" +
	"\x04user\x18\x01 \x02(\tR\x04user\"7\n" +
	"\x1dGetGroupsForUserResponseProto\x12\x16\n" +
	"\x06groups\x18\x01 \x03(\tR\x06groups2\x8f\x01\n" +
	"\x1eGetUserMappingsProtocolService\x12m\n" +
	"\x10getGroupsForUser\x12+.hadoop.common.GetGroupsForUserRequestProto\x1a,.hadoop.common.GetGroupsForUserResponseProtoB\x82\x01\n" +
	"\x1dorg.apache.hadoop.tools.protoB\x1dGetUserMappingsProtocolProtosZ<github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_common\x88\x01\x01\xa0\x01\x01"

var (
	file_GetUserMappingsProtocol_proto_rawDescOnce sync.Once
	file_GetUserMappingsProtocol_proto_rawDescData []byte
)

func file_GetUserMappingsProtocol_proto_rawDescGZIP() []byte {
	file_GetUserMappingsProtocol_proto_rawDescOnce.Do(func() {
		file_GetUserMappingsProtocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GetUserMappingsProtocol_proto_rawDesc), len(file_GetUserMappingsProtocol_proto_rawDesc)))
	})
	return file_GetUserMappingsProtocol_proto_rawDescData
}

var file_GetUserMappingsProtocol_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GetUserMappingsProtocol_proto_goTypes = []any{
	(*GetGroupsForUserRequestProto)(nil),  // 0: hadoop.common.GetGroupsForUserRequestProto
	(*GetGroupsForUserResponseProto)(nil), // 1: hadoop.common.GetGroupsForUserResponseProto
}
var file_GetUserMappingsProtocol_proto_depIdxs = []int32{
	0, // 0: hadoop.common.GetUserMappingsProtocolService.getGroupsForUser:input_type -> hadoop.common.GetGroupsForUserRequestProto
	1, // 1: hadoop.common.GetUserMappingsProtocolService.getGroupsForUser:output_type -> hadoop.common.GetGroupsForUserResponseProto
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_GetUserMappingsProtocol_proto_init() }
func file_GetUserMappingsProtocol_proto_init() {
	if File_GetUserMappingsProtocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GetUserMappingsProtocol_proto_rawDesc), len(file_GetUserMappingsProtocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_GetUserMappingsProtocol_proto_goTypes,
		DependencyIndexes: file_GetUserMappingsProtocol_proto_depIdxs,
		MessageInfos:      file_GetUserMappingsProtocol_proto_msgTypes,
	}.Build()
	File_GetUserMappingsProtocol_proto = out.File
	file_GetUserMappingsProtocol_proto_goTypes = nil
	file_GetUserMappingsProtocol_proto_depIdxs = nil
}
