//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// These .proto interfaces are private and stable.
// Please see http://wiki.apache.org/hadoop/Compatibility
// for what changes are allowed for a *stable* .proto interface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: HAServiceProtocol.proto

package hadoop_common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HAServiceStateProto int32

const (
	HAServiceStateProto_INITIALIZING HAServiceStateProto = 0
	HAServiceStateProto_ACTIVE       HAServiceStateProto = 1
	HAServiceStateProto_STANDBY      HAServiceStateProto = 2
	HAServiceStateProto_OBSERVER     HAServiceStateProto = 3
)

// Enum value maps for HAServiceStateProto.
var (
	HAServiceStateProto_name = map[int32]string{
		0: "INITIALIZING",
		1: "ACTIVE",
		2: "STANDBY",
		3: "OBSERVER",
	}
	HAServiceStateProto_value = map[string]int32{
		"INITIALIZING": 0,
		"ACTIVE":       1,
		"STANDBY":      2,
		"OBSERVER":     3,
	}
)

func (x HAServiceStateProto) Enum() *HAServiceStateProto {
	p := new(HAServiceStateProto)
	*p = x
	return p
}

func (x HAServiceStateProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HAServiceStateProto) Descriptor() protoreflect.EnumDescriptor {
	return file_HAServiceProtocol_proto_enumTypes[0].Descriptor()
}

func (HAServiceStateProto) Type() protoreflect.EnumType {
	return &file_HAServiceProtocol_proto_enumTypes[0]
}

func (x HAServiceStateProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *HAServiceStateProto) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = HAServiceStateProto(num)
	return nil
}

// Deprecated: Use HAServiceStateProto.Descriptor instead.
func (HAServiceStateProto) EnumDescriptor() ([]byte, []int) {
	return file_HAServiceProtocol_proto_rawDescGZIP(), []int{0}
}

type HARequestSource int32

const (
	HARequestSource_REQUEST_BY_USER        HARequestSource = 0
	HARequestSource_REQUEST_BY_USER_FORCED HARequestSource = 1
	HARequestSource_REQUEST_BY_ZKFC        HARequestSource = 2
)

// Enum value maps for HARequestSource.
var (
	HARequestSource_name = map[int32]string{
		0: "REQUEST_BY_USER",
		1: "REQUEST_BY_USER_FORCED",
		2: "REQUEST_BY_ZKFC",
	}
	HARequestSource_value = map[string]int32{
		"REQUEST_BY_USER":        0,
		"REQUEST_BY_USER_FORCED": 1,
		"REQUEST_BY_ZKFC":        2,
	}
)

func (x HARequestSource) Enum() *HARequestSource {
	p := new(HARequestSource)
	*p = x
	return p
}

func (x HARequestSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HARequestSource) Descriptor() protoreflect.EnumDescriptor {
	return file_HAServiceProtocol_proto_enumTypes[1].Descriptor()
}

func (HARequestSource) Type() protoreflect.EnumType {
	return &file_HAServiceProtocol_proto_enumTypes[1]
}

func (x HARequestSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *HARequestSource) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = HARequestSource(num)
	return nil
}

// Deprecated: Use HARequestSource.Descriptor instead.
func (HARequestSource) EnumDescriptor() ([]byte, []int) {
	return file_HAServiceProtocol_proto_rawDescGZIP(), []int{1}
}

type HAStateChangeRequestInfoProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqSource     *HARequestSource       `protobuf:"varint,1,req,name=reqSource,enum=hadoop.common.HARequestSource" json:"reqSource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HAStateChangeRequestInfoProto) Reset() {
	*x = HAStateChangeRequestInfoProto{}
	mi := &file_HAServiceProtocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HAStateChangeRequestInfoProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HAStateChangeRequestInfoProto) ProtoMessage() {}

func (x *HAStateChangeRequestInfoProto) ProtoReflect() protoreflect.Message {
	mi := &file_HAServiceProtocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HAStateChangeRequestInfoProto.ProtoReflect.Descriptor instead.
func (*HAStateChangeRequestInfoProto) Descriptor() ([]byte, []int) {
	return file_HAServiceProtocol_proto_rawDescGZIP(), []int{0}
}

func (x *HAStateChangeRequestInfoProto) GetReqSource() HARequestSource {
	if x != nil && x.ReqSource != nil {
		return *x.ReqSource
	}
	return HARequestSource_REQUEST_BY_USER
}

// *
// void request
type MonitorHealthRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorHealthRequestProto) Reset() {
	*x = MonitorHealthRequestProto{}
	mi := &file_HAServiceProtocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorHealthRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorHealthRequestProto) ProtoMessage() {}

func (x *MonitorHealthRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_HAServiceProtocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorHealthRequestProto.ProtoReflect.Descriptor instead.
func (*MonitorHealthRequestProto) Descriptor() ([]byte, []int) {
	return file_HAServiceProtocol_proto_rawDescGZIP(), []int{1}
}

// *
// void response
type MonitorHealthResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorHealthResponseProto) Reset() {
	*x = MonitorHealthResponseProto{}
	mi := &file_HAServiceProtocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorHealthResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorHealthResponseProto) ProtoMessage() {}

func (x *MonitorHealthResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_HAServiceProtocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorHealthResponseProto.ProtoReflect.Descriptor instead.
func (*MonitorHealthResponseProto) Descriptor() ([]byte, []int) {
	return file_HAServiceProtocol_proto_rawDescGZIP(), []int{2}
}

// *
// void request
type TransitionToActiveRequestProto struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	ReqInfo       *HAStateChangeRequestInfoProto `protobuf:"bytes,1,req,name=reqInfo" json:"reqInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionToActiveRequestProto) Reset() {
	*x = TransitionToActiveRequestProto{}
	mi := &file_HAServiceProtocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionToActiveRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionToActiveRequestProto) ProtoMessage() {}

func (x *TransitionToActiveRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_HAServiceProtocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionToActiveRequestProto.ProtoReflect.Descriptor instead.
func (*TransitionToActiveRequestProto) Descriptor() ([]byte, []int) {
	return file_HAServiceProtocol_proto_rawDescGZIP(), []int{3}
}

func (x *TransitionToActiveRequestProto) GetReqInfo() *HAStateChangeRequestInfoProto {
	if x != nil {
		return x.ReqInfo
	}
	return nil
}

// *
// void response
type TransitionToActiveResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionToActiveResponseProto) Reset() {
	*x = TransitionToActiveResponseProto{}
	mi := &file_HAServiceProtocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionToActiveResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionToActiveResponseProto) ProtoMessage() {}

func (x *TransitionToActiveResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_HAServiceProtocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionToActiveResponseProto.ProtoReflect.Descriptor instead.
func (*TransitionToActiveResponseProto) Descriptor() ([]byte, []int) {
	return file_HAServiceProtocol_proto_rawDescGZIP(), []int{4}
}

// *
// void request
type TransitionToStandbyRequestProto struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	ReqInfo       *HAStateChangeRequestInfoProto `protobuf:"bytes,1,req,name=reqInfo" json:"reqInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionToStandbyRequestProto) Reset() {
	*x = TransitionToStandbyRequestProto{}
	mi := &file_HAServiceProtocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionToStandbyRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionToStandbyRequestProto) ProtoMessage() {}

func (x *TransitionToStandbyRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_HAServiceProtocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionToStandbyRequestProto.ProtoReflect.Descriptor instead.
func (*TransitionToStandbyRequestProto) Descriptor() ([]byte, []int) {
	return file_HAServiceProtocol_proto_rawDescGZIP(), []int{5}
}

func (x *TransitionToStandbyRequestProto) GetReqInfo() *HAStateChangeRequestInfoProto {
	if x != nil {
		return x.ReqInfo
	}
	return nil
}

// *
// void response
type TransitionToStandbyResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionToStandbyResponseProto) Reset() {
	*x = TransitionToStandbyResponseProto{}
	mi := &file_HAServiceProtocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionToStandbyResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionToStandbyResponseProto) ProtoMessage() {}

func (x *TransitionToStandbyResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_HAServiceProtocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionToStandbyResponseProto.ProtoReflect.Descriptor instead.
func (*TransitionToStandbyResponseProto) Descriptor() ([]byte, []int) {
	return file_HAServiceProtocol_proto_rawDescGZIP(), []int{6}
}

// *
// void request
type TransitionToObserverRequestProto struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	ReqInfo       *HAStateChangeRequestInfoProto `protobuf:"bytes,1,req,name=reqInfo" json:"reqInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionToObserverRequestProto) Reset() {
	*x = TransitionToObserverRequestProto{}
	mi := &file_HAServiceProtocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionToObserverRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionToObserverRequestProto) ProtoMessage() {}

func (x *TransitionToObserverRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_HAServiceProtocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionToObserverRequestProto.ProtoReflect.Descriptor instead.
func (*TransitionToObserverRequestProto) Descriptor() ([]byte, []int) {
	return file_HAServiceProtocol_proto_rawDescGZIP(), []int{7}
}

func (x *TransitionToObserverRequestProto) GetReqInfo() *HAStateChangeRequestInfoProto {
	if x != nil {
		return x.ReqInfo
	}
	return nil
}

// *
// void response
type TransitionToObserverResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionToObserverResponseProto) Reset() {
	*x = TransitionToObserverResponseProto{}
	mi := &file_HAServiceProtocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionToObserverResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionToObserverResponseProto) ProtoMessage() {}

func (x *TransitionToObserverResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_HAServiceProtocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionToObserverResponseProto.ProtoReflect.Descriptor instead.
func (*TransitionToObserverResponseProto) Descriptor() ([]byte, []int) {
	return file_HAServiceProtocol_proto_rawDescGZIP(), []int{8}
}

// *
// void request
type GetServiceStatusRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceStatusRequestProto) Reset() {
	*x = GetServiceStatusRequestProto{}
	mi := &file_HAServiceProtocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceStatusRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceStatusRequestProto) ProtoMessage() {}

func (x *GetServiceStatusRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_HAServiceProtocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceStatusRequestProto.ProtoReflect.Descriptor instead.
func (*GetServiceStatusRequestProto) Descriptor() ([]byte, []int) {
	return file_HAServiceProtocol_proto_rawDescGZIP(), []int{9}
}

// *
// Returns the state of the service
type GetServiceStatusResponseProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	State *HAServiceStateProto   `protobuf:"varint,1,req,name=state,enum=hadoop.common.HAServiceStateProto" json:"state,omitempty"`
	// If state is STANDBY, indicate whether it is
	// ready to become active.
	ReadyToBecomeActive *bool `protobuf:"varint,2,opt,name=readyToBecomeActive" json:"readyToBecomeActive,omitempty"`
	// If not ready to become active, a textual explanation of why not
	NotReadyReason *string `protobuf:"bytes,3,opt,name=notReadyReason" json:"notReadyReason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetServiceStatusResponseProto) Reset() {
	*x = GetServiceStatusResponseProto{}
	mi := &file_HAServiceProtocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceStatusResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceStatusResponseProto) ProtoMessage() {}

func (x *GetServiceStatusResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_HAServiceProtocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceStatusResponseProto.ProtoReflect.Descriptor instead.
func (*GetServiceStatusResponseProto) Descriptor() ([]byte, []int) {
	return file_HAServiceProtocol_proto_rawDescGZIP(), []int{10}
}

func (x *GetServiceStatusResponseProto) GetState() HAServiceStateProto {
	if x != nil && x.State != nil {
		return *x.State
	}
	return HAServiceStateProto_INITIALIZING
}

func (x *GetServiceStatusResponseProto) GetReadyToBecomeActive() bool {
	if x != nil && x.ReadyToBecomeActive != nil {
		return *x.ReadyToBecomeActive
	}
	return false
}

func (x *GetServiceStatusResponseProto) GetNotReadyReason() string {
	if x != nil && x.NotReadyReason != nil {
		return *x.NotReadyReason
	}
	return ""
}

var File_HAServiceProtocol_proto protoreflect.FileDescriptor

const file_HAServiceProtocol_proto_rawDesc = "" +
	"\n" +
	"\x17HAServiceProtocol.proto\x12\rhadoop.common\"]\n" +
	"\x1dHAStateChangeRequestInfoProto\x12<\n" +
	"\treqSource\x18\x01 \x02(\x0e2\x1e.hadoop.common.HARequestSourceR\treqSource\"\x1b\n" +
	"\x19MonitorHealthRequestProto\"\x1c\n" +
	"\x1aMonitorHealthResponseProto\"h\n" +
	"\x1eTransitionToActiveRequestProto\x12F\n" +
	"\areqInfo\x18\x01 \x02(\v2,.hadoop.common.HAStateChangeRequestInfoProtoR\areqInfo\"!\n" +
	"\x1fTransitionToActiveResponseProto\"i\n" +
	"\x1fTransitionToStandbyRequestProto\x12F\n" +
	"\areqInfo\x18\x01 \x02(\v2,.hadoop.common.HAStateChangeRequestInfoProtoR\areqInfo\"\"\n" +
	" TransitionToStandbyResponseProto\"j\n" +
	" TransitionToObserverRequestProto\x12F\n" +
	"\areqInfo\x18\x01 \x02(\v2,.hadoop.common.HAStateChangeRequestInfoProtoR\areqInfo\"#\n" +
	"!TransitionToObserverResponseProto\"\x1e\n" +
	"\x1cGetServiceStatusRequestProto\"\xb3\x01\n" +
	"\x1dGetServiceStatusResponseProto\x128\n" +
	"\x05state\x18\x01 \x02(\x0e2\".hadoop.common.HAServiceStateProtoR\x05state\x120\n" +
	"\x13readyToBecomeActive\x18\x02 \x01(\bR\x13readyToBecomeActive\x12&\n" +
	"\x0enotReadyReason\x18\x03 \x01(\tR\x0enotReadyReason*N\n" +
	"\x13HAServiceStateProto\x12\x10\n" +
	"\fINITIALIZING\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\v\n" +
	"\aSTANDBY\x10\x02\x12\f\n" +
	"\bOBSERVER\x10\x03*W\n" +
	"\x0fHARequestSource\x12\x13\n" +
	"\x0fREQUEST_BY_USER\x10\x00\x12\x1a\n" +
	"\x16REQUEST_BY_USER_FORCED\x10\x01\x12\x13\n" +
	"\x0fREQUEST_BY_ZKFC\x10\x022\xd7\x04\n" +
	"\x18HAServiceProtocolService\x12d\n" +
	"\rmonitorHealth\x12(.hadoop.common.MonitorHealthRequestProto\x1a).hadoop.common.MonitorHealthResponseProto\x12s\n" +
	"\x12transitionToActive\x12-.hadoop.common.TransitionToActiveRequestProto\x1a..hadoop.common.TransitionToActiveResponseProto\x12v\n" +
	"\x13transitionToStandby\x12..hadoop.common.TransitionToStandbyRequestProto\x1a/.hadoop.common.TransitionToStandbyResponseProto\x12y\n" +
	"\x14transitionToObserver\x12/.hadoop.common.TransitionToObserverRequestProto\x1a0.hadoop.common.TransitionToObserverResponseProto\x12m\n" +
	"\x10getServiceStatus\x12+.hadoop.common.GetServiceStatusRequestProto\x1a,.hadoop.common.GetServiceStatusResponseProtoBy\n" +
	"\x1aorg.apache.hadoop.ha.protoB\x17HAServiceProtocolProtosZ<github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_common\x88\x01\x01\xa0\x01\x01"

var (
	file_HAServiceProtocol_proto_rawDescOnce sync.Once
	file_HAServiceProtocol_proto_rawDescData []byte
)

func file_HAServiceProtocol_proto_rawDescGZIP() []byte {
	file_HAServiceProtocol_proto_rawDescOnce.Do(func() {
		file_HAServiceProtocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_HAServiceProtocol_proto_rawDesc), len(file_HAServiceProtocol_proto_rawDesc)))
	})
	return file_HAServiceProtocol_proto_rawDescData
}

var file_HAServiceProtocol_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_HAServiceProtocol_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_HAServiceProtocol_proto_goTypes = []any{
	(HAServiceStateProto)(0),                  // 0: hadoop.common.HAServiceStateProto
	(HARequestSource)(0),                      // 1: hadoop.common.HARequestSource
	(*HAStateChangeRequestInfoProto)(nil),     // 2: hadoop.common.HAStateChangeRequestInfoProto
	(*MonitorHealthRequestProto)(nil),         // 3: hadoop.common.MonitorHealthRequestProto
	(*MonitorHealthResponseProto)(nil),        // 4: hadoop.common.MonitorHealthResponseProto
	(*TransitionToActiveRequestProto)(nil),    // 5: hadoop.common.TransitionToActiveRequestProto
	(*TransitionToActiveResponseProto)(nil),   // 6: hadoop.common.TransitionToActiveResponseProto
	(*TransitionToStandbyRequestProto)(nil),   // 7: hadoop.common.TransitionToStandbyRequestProto
	(*TransitionToStandbyResponseProto)(nil),  // 8: hadoop.common.TransitionToStandbyResponseProto
	(*TransitionToObserverRequestProto)(nil),  // 9: hadoop.common.TransitionToObserverRequestProto
	(*TransitionToObserverResponseProto)(nil), // 10: hadoop.common.TransitionToObserverResponseProto
	(*GetServiceStatusRequestProto)(nil),      // 11: hadoop.common.GetServiceStatusRequestProto
	(*GetServiceStatusResponseProto)(nil),     // 12: hadoop.common.GetServiceStatusResponseProto
}
var file_HAServiceProtocol_proto_depIdxs = []int32{
	1,  // 0: hadoop.common.HAStateChangeRequestInfoProto.reqSource:type_name -> hadoop.common.HARequestSource
	2,  // 1: hadoop.common.TransitionToActiveRequestProto.reqInfo:type_name -> hadoop.common.HAStateChangeRequestInfoProto
	2,  // 2: hadoop.common.TransitionToStandbyRequestProto.reqInfo:type_name -> hadoop.common.HAStateChangeRequestInfoProto
	2,  // 3: hadoop.common.TransitionToObserverRequestProto.reqInfo:type_name -> hadoop.common.HAStateChangeRequestInfoProto
	0,  // 4: hadoop.common.GetServiceStatusResponseProto.state:type_name -> hadoop.common.HAServiceStateProto
	3,  // 5: hadoop.common.HAServiceProtocolService.monitorHealth:input_type -> hadoop.common.MonitorHealthRequestProto
	5,  // 6: hadoop.common.HAServiceProtocolService.transitionToActive:input_type -> hadoop.common.TransitionToActiveRequestProto
	7,  // 7: hadoop.common.HAServiceProtocolService.transitionToStandby:input_type -> hadoop.common.TransitionToStandbyRequestProto
	9,  // 8: hadoop.common.HAServiceProtocolService.transitionToObserver:input_type -> hadoop.common.TransitionToObserverRequestProto
	11, // 9: hadoop.common.HAServiceProtocolService.getServiceStatus:input_type -> hadoop.common.GetServiceStatusRequestProto
	4,  // 10: hadoop.common.HAServiceProtocolService.monitorHealth:output_type -> hadoop.common.MonitorHealthResponseProto
	6,  // 11: hadoop.common.HAServiceProtocolService.transitionToActive:output_type -> hadoop.common.TransitionToActiveResponseProto
	8,  // 12: hadoop.common.HAServiceProtocolService.transitionToStandby:output_type -> hadoop.common.TransitionToStandbyResponseProto
	10, // 13: hadoop.common.HAServiceProtocolService.transitionToObserver:output_type -> hadoop.common.TransitionToObserverResponseProto
	12, // 14: hadoop.common.HAServiceProtocolService.getServiceStatus:output_type -> hadoop.common.GetServiceStatusResponseProto
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_HAServiceProtocol_proto_init() }
func file_HAServiceProtocol_proto_init() {
	if File_HAServiceProtocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_HAServiceProtocol_proto_rawDesc), len(file_HAServiceProtocol_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_HAServiceProtocol_proto_goTypes,
		DependencyIndexes: file_HAServiceProtocol_proto_depIdxs,
		EnumInfos:         file_HAServiceProtocol_proto_enumTypes,
		MessageInfos:      file_HAServiceProtocol_proto_msgTypes,
	}.Build()
	File_HAServiceProtocol_proto = out.File
	file_HAServiceProtocol_proto_goTypes = nil
	file_HAServiceProtocol_proto_depIdxs = nil
}
