//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// These .proto interfaces are private and stable.
// Please see http://wiki.apache.org/hadoop/Compatibility
// for what changes are allowed for a *stable* .proto interface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: IpcConnectionContext.proto

package hadoop_common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Spec for UserInformationProto is specified in ProtoUtil#makeIpcConnectionContext
type UserInformationProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EffectiveUser *string                `protobuf:"bytes,1,opt,name=effectiveUser" json:"effectiveUser,omitempty"`
	RealUser      *string                `protobuf:"bytes,2,opt,name=realUser" json:"realUser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInformationProto) Reset() {
	*x = UserInformationProto{}
	mi := &file_IpcConnectionContext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInformationProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInformationProto) ProtoMessage() {}

func (x *UserInformationProto) ProtoReflect() protoreflect.Message {
	mi := &file_IpcConnectionContext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInformationProto.ProtoReflect.Descriptor instead.
func (*UserInformationProto) Descriptor() ([]byte, []int) {
	return file_IpcConnectionContext_proto_rawDescGZIP(), []int{0}
}

func (x *UserInformationProto) GetEffectiveUser() string {
	if x != nil && x.EffectiveUser != nil {
		return *x.EffectiveUser
	}
	return ""
}

func (x *UserInformationProto) GetRealUser() string {
	if x != nil && x.RealUser != nil {
		return *x.RealUser
	}
	return ""
}

// *
// The connection context is sent as part of the connection establishment.
// It establishes the context for ALL Rpc calls within the connection.
type IpcConnectionContextProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UserInfo beyond what is determined as part of security handshake
	// at connection time (kerberos, tokens etc).
	UserInfo *UserInformationProto `protobuf:"bytes,2,opt,name=userInfo" json:"userInfo,omitempty"`
	// Protocol name for next rpc layer.
	// The client created a proxy with this protocol name
	Protocol      *string `protobuf:"bytes,3,opt,name=protocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpcConnectionContextProto) Reset() {
	*x = IpcConnectionContextProto{}
	mi := &file_IpcConnectionContext_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpcConnectionContextProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpcConnectionContextProto) ProtoMessage() {}

func (x *IpcConnectionContextProto) ProtoReflect() protoreflect.Message {
	mi := &file_IpcConnectionContext_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpcConnectionContextProto.ProtoReflect.Descriptor instead.
func (*IpcConnectionContextProto) Descriptor() ([]byte, []int) {
	return file_IpcConnectionContext_proto_rawDescGZIP(), []int{1}
}

func (x *IpcConnectionContextProto) GetUserInfo() *UserInformationProto {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *IpcConnectionContextProto) GetProtocol() string {
	if x != nil && x.Protocol != nil {
		return *x.Protocol
	}
	return ""
}

var File_IpcConnectionContext_proto protoreflect.FileDescriptor

const file_IpcConnectionContext_proto_rawDesc = "" +
	"\n" +
	"\x1aIpcConnectionContext.proto\x12\rhadoop.common\"X\n" +
	"\x14UserInformationProto\x12$\n" +
	"\reffectiveUser\x18\x01 \x01(\tR\reffectiveUser\x12\x1a\n" +
	"\brealUser\x18\x02 \x01(\tR\brealUser\"x\n" +
	"\x19IpcConnectionContextProto\x12?\n" +
	"\buserInfo\x18\x02 \x01(\v2#.hadoop.common.UserInformationProtoR\buserInfo\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocolB}\n" +
	"\x1eorg.apache.hadoop.ipc.protobufB\x1aIpcConnectionContextProtosZ<github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_common\xa0\x01\x01"

var (
	file_IpcConnectionContext_proto_rawDescOnce sync.Once
	file_IpcConnectionContext_proto_rawDescData []byte
)

func file_IpcConnectionContext_proto_rawDescGZIP() []byte {
	file_IpcConnectionContext_proto_rawDescOnce.Do(func() {
		file_IpcConnectionContext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_IpcConnectionContext_proto_rawDesc), len(file_IpcConnectionContext_proto_rawDesc)))
	})
	return file_IpcConnectionContext_proto_rawDescData
}

var file_IpcConnectionContext_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_IpcConnectionContext_proto_goTypes = []any{
	(*UserInformationProto)(nil),      // 0: hadoop.common.UserInformationProto
	(*IpcConnectionContextProto)(nil), // 1: hadoop.common.IpcConnectionContextProto
}
var file_IpcConnectionContext_proto_depIdxs = []int32{
	0, // 0: hadoop.common.IpcConnectionContextProto.userInfo:type_name -> hadoop.common.UserInformationProto
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_IpcConnectionContext_proto_init() }
func file_IpcConnectionContext_proto_init() {
	if File_IpcConnectionContext_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_IpcConnectionContext_proto_rawDesc), len(file_IpcConnectionContext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_IpcConnectionContext_proto_goTypes,
		DependencyIndexes: file_IpcConnectionContext_proto_depIdxs,
		MessageInfos:      file_IpcConnectionContext_proto_msgTypes,
	}.Build()
	File_IpcConnectionContext_proto = out.File
	file_IpcConnectionContext_proto_goTypes = nil
	file_IpcConnectionContext_proto_depIdxs = nil
}
