//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// These .proto interfaces are private and stable.
// Please see http://wiki.apache.org/hadoop/Compatibility
// for what changes are allowed for a *stable* .proto interface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: ProtocolInfo.proto

package hadoop_common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Request to get protocol versions for all supported rpc kinds.
type GetProtocolVersionsRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      *string                `protobuf:"bytes,1,req,name=protocol" json:"protocol,omitempty"` // Protocol name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProtocolVersionsRequestProto) Reset() {
	*x = GetProtocolVersionsRequestProto{}
	mi := &file_ProtocolInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProtocolVersionsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProtocolVersionsRequestProto) ProtoMessage() {}

func (x *GetProtocolVersionsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_ProtocolInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProtocolVersionsRequestProto.ProtoReflect.Descriptor instead.
func (*GetProtocolVersionsRequestProto) Descriptor() ([]byte, []int) {
	return file_ProtocolInfo_proto_rawDescGZIP(), []int{0}
}

func (x *GetProtocolVersionsRequestProto) GetProtocol() string {
	if x != nil && x.Protocol != nil {
		return *x.Protocol
	}
	return ""
}

// *
// Protocol version with corresponding rpc kind.
type ProtocolVersionProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcKind       *string                `protobuf:"bytes,1,req,name=rpcKind" json:"rpcKind,omitempty"`    //RPC kind
	Versions      []uint64               `protobuf:"varint,2,rep,name=versions" json:"versions,omitempty"` //Protocol version corresponding to the rpc kind.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolVersionProto) Reset() {
	*x = ProtocolVersionProto{}
	mi := &file_ProtocolInfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolVersionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolVersionProto) ProtoMessage() {}

func (x *ProtocolVersionProto) ProtoReflect() protoreflect.Message {
	mi := &file_ProtocolInfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolVersionProto.ProtoReflect.Descriptor instead.
func (*ProtocolVersionProto) Descriptor() ([]byte, []int) {
	return file_ProtocolInfo_proto_rawDescGZIP(), []int{1}
}

func (x *ProtocolVersionProto) GetRpcKind() string {
	if x != nil && x.RpcKind != nil {
		return *x.RpcKind
	}
	return ""
}

func (x *ProtocolVersionProto) GetVersions() []uint64 {
	if x != nil {
		return x.Versions
	}
	return nil
}

// *
// Get protocol version response.
type GetProtocolVersionsResponseProto struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	ProtocolVersions []*ProtocolVersionProto `protobuf:"bytes,1,rep,name=protocolVersions" json:"protocolVersions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetProtocolVersionsResponseProto) Reset() {
	*x = GetProtocolVersionsResponseProto{}
	mi := &file_ProtocolInfo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProtocolVersionsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProtocolVersionsResponseProto) ProtoMessage() {}

func (x *GetProtocolVersionsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_ProtocolInfo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProtocolVersionsResponseProto.ProtoReflect.Descriptor instead.
func (*GetProtocolVersionsResponseProto) Descriptor() ([]byte, []int) {
	return file_ProtocolInfo_proto_rawDescGZIP(), []int{2}
}

func (x *GetProtocolVersionsResponseProto) GetProtocolVersions() []*ProtocolVersionProto {
	if x != nil {
		return x.ProtocolVersions
	}
	return nil
}

// *
// Get protocol signature request.
type GetProtocolSignatureRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      *string                `protobuf:"bytes,1,req,name=protocol" json:"protocol,omitempty"` // Protocol name
	RpcKind       *string                `protobuf:"bytes,2,req,name=rpcKind" json:"rpcKind,omitempty"`   // RPC kind
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProtocolSignatureRequestProto) Reset() {
	*x = GetProtocolSignatureRequestProto{}
	mi := &file_ProtocolInfo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProtocolSignatureRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProtocolSignatureRequestProto) ProtoMessage() {}

func (x *GetProtocolSignatureRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_ProtocolInfo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProtocolSignatureRequestProto.ProtoReflect.Descriptor instead.
func (*GetProtocolSignatureRequestProto) Descriptor() ([]byte, []int) {
	return file_ProtocolInfo_proto_rawDescGZIP(), []int{3}
}

func (x *GetProtocolSignatureRequestProto) GetProtocol() string {
	if x != nil && x.Protocol != nil {
		return *x.Protocol
	}
	return ""
}

func (x *GetProtocolSignatureRequestProto) GetRpcKind() string {
	if x != nil && x.RpcKind != nil {
		return *x.RpcKind
	}
	return ""
}

// *
// Get protocol signature response.
type GetProtocolSignatureResponseProto struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	ProtocolSignature []*ProtocolSignatureProto `protobuf:"bytes,1,rep,name=protocolSignature" json:"protocolSignature,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetProtocolSignatureResponseProto) Reset() {
	*x = GetProtocolSignatureResponseProto{}
	mi := &file_ProtocolInfo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProtocolSignatureResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProtocolSignatureResponseProto) ProtoMessage() {}

func (x *GetProtocolSignatureResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_ProtocolInfo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProtocolSignatureResponseProto.ProtoReflect.Descriptor instead.
func (*GetProtocolSignatureResponseProto) Descriptor() ([]byte, []int) {
	return file_ProtocolInfo_proto_rawDescGZIP(), []int{4}
}

func (x *GetProtocolSignatureResponseProto) GetProtocolSignature() []*ProtocolSignatureProto {
	if x != nil {
		return x.ProtocolSignature
	}
	return nil
}

type ProtocolSignatureProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *uint64                `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	Methods       []uint32               `protobuf:"varint,2,rep,name=methods" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolSignatureProto) Reset() {
	*x = ProtocolSignatureProto{}
	mi := &file_ProtocolInfo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolSignatureProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolSignatureProto) ProtoMessage() {}

func (x *ProtocolSignatureProto) ProtoReflect() protoreflect.Message {
	mi := &file_ProtocolInfo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolSignatureProto.ProtoReflect.Descriptor instead.
func (*ProtocolSignatureProto) Descriptor() ([]byte, []int) {
	return file_ProtocolInfo_proto_rawDescGZIP(), []int{5}
}

func (x *ProtocolSignatureProto) GetVersion() uint64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *ProtocolSignatureProto) GetMethods() []uint32 {
	if x != nil {
		return x.Methods
	}
	return nil
}

var File_ProtocolInfo_proto protoreflect.FileDescriptor

const file_ProtocolInfo_proto_rawDesc = "" +
	"\n" +
	"\x12ProtocolInfo.proto\x12\rhadoop.common\"=\n" +
	"\x1fGetProtocolVersionsRequestProto\x12\x1a\n" +
	"\bprotocol\x18\x01 \x02(\tR\bprotocol\"L\n" +
	"\x14ProtocolVersionProto\x12\x18\n" +
	"\arpcKind\x18\x01 \x02(\tR\arpcKind\x12\x1a\n" +
	"\bversions\x18\x02 \x03(\x04R\bversions\"s\n" +
	" GetProtocolVersionsResponseProto\x12O\n" +
	"\x10protocolVersions\x18\x01 \x03(\v2#.hadoop.common.ProtocolVersionProtoR\x10protocolVersions\"X\n" +
	" GetProtocolSignatureRequestProto\x12\x1a\n" +
	"\bprotocol\x18\x01 \x02(\tR\bprotocol\x12\x18\n" +
	"\arpcKind\x18\x02 \x02(\tR\arpcKind\"x\n" +
	"!GetProtocolSignatureResponseProto\x12S\n" +
	"\x11protocolSignature\x18\x01 \x03(\v2%.hadoop.common.ProtocolSignatureProtoR\x11protocolSignature\"L\n" +
	"\x16ProtocolSignatureProto\x12\x18\n" +
	"\aversion\x18\x01 \x02(\x04R\aversion\x12\x18\n" +
	"\amethods\x18\x02 \x03(\rR\amethods2\x88\x02\n" +
	"\x13ProtocolInfoService\x12v\n" +
	"\x13getProtocolVersions\x12..hadoop.common.GetProtocolVersionsRequestProto\x1a/.hadoop.common.GetProtocolVersionsResponseProto\x12y\n" +
	"\x14getProtocolSignature\x12/.hadoop.common.GetProtocolSignatureRequestProto\x1a0.hadoop.common.GetProtocolSignatureResponseProtoBx\n" +
	"\x1eorg.apache.hadoop.ipc.protobufB\x12ProtocolInfoProtosZ<github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_common\x88\x01\x01\xa0\x01\x01"

var (
	file_ProtocolInfo_proto_rawDescOnce sync.Once
	file_ProtocolInfo_proto_rawDescData []byte
)

func file_ProtocolInfo_proto_rawDescGZIP() []byte {
	file_ProtocolInfo_proto_rawDescOnce.Do(func() {
		file_ProtocolInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ProtocolInfo_proto_rawDesc), len(file_ProtocolInfo_proto_rawDesc)))
	})
	return file_ProtocolInfo_proto_rawDescData
}

var file_ProtocolInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ProtocolInfo_proto_goTypes = []any{
	(*GetProtocolVersionsRequestProto)(nil),   // 0: hadoop.common.GetProtocolVersionsRequestProto
	(*ProtocolVersionProto)(nil),              // 1: hadoop.common.ProtocolVersionProto
	(*GetProtocolVersionsResponseProto)(nil),  // 2: hadoop.common.GetProtocolVersionsResponseProto
	(*GetProtocolSignatureRequestProto)(nil),  // 3: hadoop.common.GetProtocolSignatureRequestProto
	(*GetProtocolSignatureResponseProto)(nil), // 4: hadoop.common.GetProtocolSignatureResponseProto
	(*ProtocolSignatureProto)(nil),            // 5: hadoop.common.ProtocolSignatureProto
}
var file_ProtocolInfo_proto_depIdxs = []int32{
	1, // 0: hadoop.common.GetProtocolVersionsResponseProto.protocolVersions:type_name -> hadoop.common.ProtocolVersionProto
	5, // 1: hadoop.common.GetProtocolSignatureResponseProto.protocolSignature:type_name -> hadoop.common.ProtocolSignatureProto
	0, // 2: hadoop.common.ProtocolInfoService.getProtocolVersions:input_type -> hadoop.common.GetProtocolVersionsRequestProto
	3, // 3: hadoop.common.ProtocolInfoService.getProtocolSignature:input_type -> hadoop.common.GetProtocolSignatureRequestProto
	2, // 4: hadoop.common.ProtocolInfoService.getProtocolVersions:output_type -> hadoop.common.GetProtocolVersionsResponseProto
	4, // 5: hadoop.common.ProtocolInfoService.getProtocolSignature:output_type -> hadoop.common.GetProtocolSignatureResponseProto
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ProtocolInfo_proto_init() }
func file_ProtocolInfo_proto_init() {
	if File_ProtocolInfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ProtocolInfo_proto_rawDesc), len(file_ProtocolInfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ProtocolInfo_proto_goTypes,
		DependencyIndexes: file_ProtocolInfo_proto_depIdxs,
		MessageInfos:      file_ProtocolInfo_proto_msgTypes,
	}.Build()
	File_ProtocolInfo_proto = out.File
	file_ProtocolInfo_proto_goTypes = nil
	file_ProtocolInfo_proto_depIdxs = nil
}
