//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// These .proto interfaces are private and stable.
// Please see http://wiki.apache.org/hadoop/Compatibility
// for what changes are allowed for a *stable* .proto interface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: ProtobufRpcEngine.proto

package hadoop_common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// This message is the header for the Protobuf Rpc Engine
// when sending a RPC request from  RPC client to the RPC server.
// The actual request (serialized as protobuf) follows this request.
//
// No special header is needed for the Rpc Response for Protobuf Rpc Engine.
// The normal RPC response header (see RpcHeader.proto) are sufficient.
type RequestHeaderProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Name of the RPC method
	MethodName *string `protobuf:"bytes,1,req,name=methodName" json:"methodName,omitempty"`
	// *
	// RPCs for a particular interface (ie protocol) are done using a
	// IPC connection that is setup using rpcProxy.
	// The rpcProxy's has a declared protocol name that is
	// sent form client to server at connection time.
	//
	// Each Rpc call also sends a protocol name
	// (called declaringClassprotocolName). This name is usually the same
	// as the connection protocol name except in some cases.
	// For example metaProtocols such ProtocolInfoProto which get metainfo
	// about the protocol reuse the connection but need to indicate that
	// the actual protocol is different (i.e. the protocol is
	// ProtocolInfoProto) since they reuse the connection; in this case
	// the declaringClassProtocolName field is set to the ProtocolInfoProto
	DeclaringClassProtocolName *string `protobuf:"bytes,2,req,name=declaringClassProtocolName" json:"declaringClassProtocolName,omitempty"`
	// * protocol version of class declaring the called method
	ClientProtocolVersion *uint64 `protobuf:"varint,3,req,name=clientProtocolVersion" json:"clientProtocolVersion,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RequestHeaderProto) Reset() {
	*x = RequestHeaderProto{}
	mi := &file_ProtobufRpcEngine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHeaderProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHeaderProto) ProtoMessage() {}

func (x *RequestHeaderProto) ProtoReflect() protoreflect.Message {
	mi := &file_ProtobufRpcEngine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHeaderProto.ProtoReflect.Descriptor instead.
func (*RequestHeaderProto) Descriptor() ([]byte, []int) {
	return file_ProtobufRpcEngine_proto_rawDescGZIP(), []int{0}
}

func (x *RequestHeaderProto) GetMethodName() string {
	if x != nil && x.MethodName != nil {
		return *x.MethodName
	}
	return ""
}

func (x *RequestHeaderProto) GetDeclaringClassProtocolName() string {
	if x != nil && x.DeclaringClassProtocolName != nil {
		return *x.DeclaringClassProtocolName
	}
	return ""
}

func (x *RequestHeaderProto) GetClientProtocolVersion() uint64 {
	if x != nil && x.ClientProtocolVersion != nil {
		return *x.ClientProtocolVersion
	}
	return 0
}

var File_ProtobufRpcEngine_proto protoreflect.FileDescriptor

const file_ProtobufRpcEngine_proto_rawDesc = "" +
	"\n" +
	"\x17ProtobufRpcEngine.proto\x12\rhadoop.common\"\xaa\x01\n" +
	"\x12RequestHeaderProto\x12\x1e\n" +
	"\n" +
	"methodName\x18\x01 \x02(\tR\n" +
	"methodName\x12>\n" +
	"\x1adeclaringClassProtocolName\x18\x02 \x02(\tR\x1adeclaringClassProtocolName\x124\n" +
	"\x15clientProtocolVersion\x18\x03 \x02(\x04R\x15clientProtocolVersionBz\n" +
	"\x1eorg.apache.hadoop.ipc.protobufB\x17ProtobufRpcEngineProtosZ<github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_common\xa0\x01\x01"

var (
	file_ProtobufRpcEngine_proto_rawDescOnce sync.Once
	file_ProtobufRpcEngine_proto_rawDescData []byte
)

func file_ProtobufRpcEngine_proto_rawDescGZIP() []byte {
	file_ProtobufRpcEngine_proto_rawDescOnce.Do(func() {
		file_ProtobufRpcEngine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ProtobufRpcEngine_proto_rawDesc), len(file_ProtobufRpcEngine_proto_rawDesc)))
	})
	return file_ProtobufRpcEngine_proto_rawDescData
}

var file_ProtobufRpcEngine_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ProtobufRpcEngine_proto_goTypes = []any{
	(*RequestHeaderProto)(nil), // 0: hadoop.common.RequestHeaderProto
}
var file_ProtobufRpcEngine_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ProtobufRpcEngine_proto_init() }
func file_ProtobufRpcEngine_proto_init() {
	if File_ProtobufRpcEngine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ProtobufRpcEngine_proto_rawDesc), len(file_ProtobufRpcEngine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ProtobufRpcEngine_proto_goTypes,
		DependencyIndexes: file_ProtobufRpcEngine_proto_depIdxs,
		MessageInfos:      file_ProtobufRpcEngine_proto_msgTypes,
	}.Build()
	File_ProtobufRpcEngine_proto = out.File
	file_ProtobufRpcEngine_proto_goTypes = nil
	file_ProtobufRpcEngine_proto_depIdxs = nil
}
