//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// These .proto interfaces are private and stable.
// Please see http://wiki.apache.org/hadoop/Compatibility
// for what changes are allowed for a *stable* .proto interface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: RefreshUserMappingsProtocol.proto

package hadoop_common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
//
//	Refresh user to group mappings request.
type RefreshUserToGroupsMappingsRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshUserToGroupsMappingsRequestProto) Reset() {
	*x = RefreshUserToGroupsMappingsRequestProto{}
	mi := &file_RefreshUserMappingsProtocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshUserToGroupsMappingsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshUserToGroupsMappingsRequestProto) ProtoMessage() {}

func (x *RefreshUserToGroupsMappingsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_RefreshUserMappingsProtocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshUserToGroupsMappingsRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshUserToGroupsMappingsRequestProto) Descriptor() ([]byte, []int) {
	return file_RefreshUserMappingsProtocol_proto_rawDescGZIP(), []int{0}
}

// *
// void response
type RefreshUserToGroupsMappingsResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshUserToGroupsMappingsResponseProto) Reset() {
	*x = RefreshUserToGroupsMappingsResponseProto{}
	mi := &file_RefreshUserMappingsProtocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshUserToGroupsMappingsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshUserToGroupsMappingsResponseProto) ProtoMessage() {}

func (x *RefreshUserToGroupsMappingsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_RefreshUserMappingsProtocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshUserToGroupsMappingsResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshUserToGroupsMappingsResponseProto) Descriptor() ([]byte, []int) {
	return file_RefreshUserMappingsProtocol_proto_rawDescGZIP(), []int{1}
}

// *
// Refresh superuser configuration request.
type RefreshSuperUserGroupsConfigurationRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSuperUserGroupsConfigurationRequestProto) Reset() {
	*x = RefreshSuperUserGroupsConfigurationRequestProto{}
	mi := &file_RefreshUserMappingsProtocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSuperUserGroupsConfigurationRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSuperUserGroupsConfigurationRequestProto) ProtoMessage() {}

func (x *RefreshSuperUserGroupsConfigurationRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_RefreshUserMappingsProtocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSuperUserGroupsConfigurationRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshSuperUserGroupsConfigurationRequestProto) Descriptor() ([]byte, []int) {
	return file_RefreshUserMappingsProtocol_proto_rawDescGZIP(), []int{2}
}

// *
// void response
type RefreshSuperUserGroupsConfigurationResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSuperUserGroupsConfigurationResponseProto) Reset() {
	*x = RefreshSuperUserGroupsConfigurationResponseProto{}
	mi := &file_RefreshUserMappingsProtocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSuperUserGroupsConfigurationResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSuperUserGroupsConfigurationResponseProto) ProtoMessage() {}

func (x *RefreshSuperUserGroupsConfigurationResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_RefreshUserMappingsProtocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSuperUserGroupsConfigurationResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshSuperUserGroupsConfigurationResponseProto) Descriptor() ([]byte, []int) {
	return file_RefreshUserMappingsProtocol_proto_rawDescGZIP(), []int{3}
}

var File_RefreshUserMappingsProtocol_proto protoreflect.FileDescriptor

const file_RefreshUserMappingsProtocol_proto_rawDesc = "" +
	"\n" +
	"!RefreshUserMappingsProtocol.proto\x12\rhadoop.common\")\n" +
	"'RefreshUserToGroupsMappingsRequestProto\"*\n" +
	"(RefreshUserToGroupsMappingsResponseProto\"1\n" +
	"/RefreshSuperUserGroupsConfigurationRequestProto\"2\n" +
	"0RefreshSuperUserGroupsConfigurationResponseProto2\xde\x02\n" +
	"\"RefreshUserMappingsProtocolService\x12\x8e\x01\n" +
	"\x1brefreshUserToGroupsMappings\x126.hadoop.common.RefreshUserToGroupsMappingsRequestProto\x1a7.hadoop.common.RefreshUserToGroupsMappingsResponseProto\x12\xa6\x01\n" +
	"#refreshSuperUserGroupsConfiguration\x12>.hadoop.common.RefreshSuperUserGroupsConfigurationRequestProto\x1a?.hadoop.common.RefreshSuperUserGroupsConfigurationResponseProtoB\x89\x01\n" +
	" org.apache.hadoop.security.protoB!RefreshUserMappingsProtocolProtosZ<github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_common\x88\x01\x01\xa0\x01\x01"

var (
	file_RefreshUserMappingsProtocol_proto_rawDescOnce sync.Once
	file_RefreshUserMappingsProtocol_proto_rawDescData []byte
)

func file_RefreshUserMappingsProtocol_proto_rawDescGZIP() []byte {
	file_RefreshUserMappingsProtocol_proto_rawDescOnce.Do(func() {
		file_RefreshUserMappingsProtocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_RefreshUserMappingsProtocol_proto_rawDesc), len(file_RefreshUserMappingsProtocol_proto_rawDesc)))
	})
	return file_RefreshUserMappingsProtocol_proto_rawDescData
}

var file_RefreshUserMappingsProtocol_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_RefreshUserMappingsProtocol_proto_goTypes = []any{
	(*RefreshUserToGroupsMappingsRequestProto)(nil),          // 0: hadoop.common.RefreshUserToGroupsMappingsRequestProto
	(*RefreshUserToGroupsMappingsResponseProto)(nil),         // 1: hadoop.common.RefreshUserToGroupsMappingsResponseProto
	(*RefreshSuperUserGroupsConfigurationRequestProto)(nil),  // 2: hadoop.common.RefreshSuperUserGroupsConfigurationRequestProto
	(*RefreshSuperUserGroupsConfigurationResponseProto)(nil), // 3: hadoop.common.RefreshSuperUserGroupsConfigurationResponseProto
}
var file_RefreshUserMappingsProtocol_proto_depIdxs = []int32{
	0, // 0: hadoop.common.RefreshUserMappingsProtocolService.refreshUserToGroupsMappings:input_type -> hadoop.common.RefreshUserToGroupsMappingsRequestProto
	2, // 1: hadoop.common.RefreshUserMappingsProtocolService.refreshSuperUserGroupsConfiguration:input_type -> hadoop.common.RefreshSuperUserGroupsConfigurationRequestProto
	1, // 2: hadoop.common.RefreshUserMappingsProtocolService.refreshUserToGroupsMappings:output_type -> hadoop.common.RefreshUserToGroupsMappingsResponseProto
	3, // 3: hadoop.common.RefreshUserMappingsProtocolService.refreshSuperUserGroupsConfiguration:output_type -> hadoop.common.RefreshSuperUserGroupsConfigurationResponseProto
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_RefreshUserMappingsProtocol_proto_init() }
func file_RefreshUserMappingsProtocol_proto_init() {
	if File_RefreshUserMappingsProtocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_RefreshUserMappingsProtocol_proto_rawDesc), len(file_RefreshUserMappingsProtocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_RefreshUserMappingsProtocol_proto_goTypes,
		DependencyIndexes: file_RefreshUserMappingsProtocol_proto_depIdxs,
		MessageInfos:      file_RefreshUserMappingsProtocol_proto_msgTypes,
	}.Build()
	File_RefreshUserMappingsProtocol_proto = out.File
	file_RefreshUserMappingsProtocol_proto_goTypes = nil
	file_RefreshUserMappingsProtocol_proto_depIdxs = nil
}
