//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// These .proto interfaces are private and stable.
// Please see http://wiki.apache.org/hadoop/Compatibility
// for what changes are allowed for a *stable* .proto interface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: RefreshCallQueueProtocol.proto

package hadoop_common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
//
//	Refresh callqueue request.
type RefreshCallQueueRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshCallQueueRequestProto) Reset() {
	*x = RefreshCallQueueRequestProto{}
	mi := &file_RefreshCallQueueProtocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshCallQueueRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshCallQueueRequestProto) ProtoMessage() {}

func (x *RefreshCallQueueRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_RefreshCallQueueProtocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshCallQueueRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshCallQueueRequestProto) Descriptor() ([]byte, []int) {
	return file_RefreshCallQueueProtocol_proto_rawDescGZIP(), []int{0}
}

// *
// void response.
type RefreshCallQueueResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshCallQueueResponseProto) Reset() {
	*x = RefreshCallQueueResponseProto{}
	mi := &file_RefreshCallQueueProtocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshCallQueueResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshCallQueueResponseProto) ProtoMessage() {}

func (x *RefreshCallQueueResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_RefreshCallQueueProtocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshCallQueueResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshCallQueueResponseProto) Descriptor() ([]byte, []int) {
	return file_RefreshCallQueueProtocol_proto_rawDescGZIP(), []int{1}
}

var File_RefreshCallQueueProtocol_proto protoreflect.FileDescriptor

const file_RefreshCallQueueProtocol_proto_rawDesc = "" +
	"\n" +
	"\x1eRefreshCallQueueProtocol.proto\x12\rhadoop.common\"\x1e\n" +
	"\x1cRefreshCallQueueRequestProto\"\x1f\n" +
	"\x1dRefreshCallQueueResponseProto2\x90\x01\n" +
	"\x1fRefreshCallQueueProtocolService\x12m\n" +
	"\x10refreshCallQueue\x12+.hadoop.common.RefreshCallQueueRequestProto\x1a,.hadoop.common.RefreshCallQueueResponseProtoB\x81\x01\n" +
	"\x1borg.apache.hadoop.ipc.protoB\x1eRefreshCallQueueProtocolProtosZ<github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_common\x88\x01\x01\xa0\x01\x01"

var (
	file_RefreshCallQueueProtocol_proto_rawDescOnce sync.Once
	file_RefreshCallQueueProtocol_proto_rawDescData []byte
)

func file_RefreshCallQueueProtocol_proto_rawDescGZIP() []byte {
	file_RefreshCallQueueProtocol_proto_rawDescOnce.Do(func() {
		file_RefreshCallQueueProtocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_RefreshCallQueueProtocol_proto_rawDesc), len(file_RefreshCallQueueProtocol_proto_rawDesc)))
	})
	return file_RefreshCallQueueProtocol_proto_rawDescData
}

var file_RefreshCallQueueProtocol_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_RefreshCallQueueProtocol_proto_goTypes = []any{
	(*RefreshCallQueueRequestProto)(nil),  // 0: hadoop.common.RefreshCallQueueRequestProto
	(*RefreshCallQueueResponseProto)(nil), // 1: hadoop.common.RefreshCallQueueResponseProto
}
var file_RefreshCallQueueProtocol_proto_depIdxs = []int32{
	0, // 0: hadoop.common.RefreshCallQueueProtocolService.refreshCallQueue:input_type -> hadoop.common.RefreshCallQueueRequestProto
	1, // 1: hadoop.common.RefreshCallQueueProtocolService.refreshCallQueue:output_type -> hadoop.common.RefreshCallQueueResponseProto
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_RefreshCallQueueProtocol_proto_init() }
func file_RefreshCallQueueProtocol_proto_init() {
	if File_RefreshCallQueueProtocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_RefreshCallQueueProtocol_proto_rawDesc), len(file_RefreshCallQueueProtocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_RefreshCallQueueProtocol_proto_goTypes,
		DependencyIndexes: file_RefreshCallQueueProtocol_proto_depIdxs,
		MessageInfos:      file_RefreshCallQueueProtocol_proto_msgTypes,
	}.Build()
	File_RefreshCallQueueProtocol_proto = out.File
	file_RefreshCallQueueProtocol_proto_goTypes = nil
	file_RefreshCallQueueProtocol_proto_depIdxs = nil
}
