//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// These .proto interfaces are private and stable.
// Please see http://wiki.apache.org/hadoop/Compatibility
// for what changes are allowed for a *stable* .proto interface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: RefreshAuthorizationPolicyProtocol.proto

package hadoop_common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
//
//	Refresh service acl request.
type RefreshServiceAclRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshServiceAclRequestProto) Reset() {
	*x = RefreshServiceAclRequestProto{}
	mi := &file_RefreshAuthorizationPolicyProtocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshServiceAclRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshServiceAclRequestProto) ProtoMessage() {}

func (x *RefreshServiceAclRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_RefreshAuthorizationPolicyProtocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshServiceAclRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshServiceAclRequestProto) Descriptor() ([]byte, []int) {
	return file_RefreshAuthorizationPolicyProtocol_proto_rawDescGZIP(), []int{0}
}

// *
// void response
type RefreshServiceAclResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshServiceAclResponseProto) Reset() {
	*x = RefreshServiceAclResponseProto{}
	mi := &file_RefreshAuthorizationPolicyProtocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshServiceAclResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshServiceAclResponseProto) ProtoMessage() {}

func (x *RefreshServiceAclResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_RefreshAuthorizationPolicyProtocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshServiceAclResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshServiceAclResponseProto) Descriptor() ([]byte, []int) {
	return file_RefreshAuthorizationPolicyProtocol_proto_rawDescGZIP(), []int{1}
}

var File_RefreshAuthorizationPolicyProtocol_proto protoreflect.FileDescriptor

const file_RefreshAuthorizationPolicyProtocol_proto_rawDesc = "" +
	"\n" +
	"(RefreshAuthorizationPolicyProtocol.proto\x12\rhadoop.common\"\x1f\n" +
	"\x1dRefreshServiceAclRequestProto\" \n" +
	"\x1eRefreshServiceAclResponseProto2\x9d\x01\n" +
	")RefreshAuthorizationPolicyProtocolService\x12p\n" +
	"\x11refreshServiceAcl\x12,.hadoop.common.RefreshServiceAclRequestProto\x1a-.hadoop.common.RefreshServiceAclResponseProtoB\x90\x01\n" +
	" org.apache.hadoop.security.protoB(RefreshAuthorizationPolicyProtocolProtosZ<github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_common\x88\x01\x01\xa0\x01\x01"

var (
	file_RefreshAuthorizationPolicyProtocol_proto_rawDescOnce sync.Once
	file_RefreshAuthorizationPolicyProtocol_proto_rawDescData []byte
)

func file_RefreshAuthorizationPolicyProtocol_proto_rawDescGZIP() []byte {
	file_RefreshAuthorizationPolicyProtocol_proto_rawDescOnce.Do(func() {
		file_RefreshAuthorizationPolicyProtocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_RefreshAuthorizationPolicyProtocol_proto_rawDesc), len(file_RefreshAuthorizationPolicyProtocol_proto_rawDesc)))
	})
	return file_RefreshAuthorizationPolicyProtocol_proto_rawDescData
}

var file_RefreshAuthorizationPolicyProtocol_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_RefreshAuthorizationPolicyProtocol_proto_goTypes = []any{
	(*RefreshServiceAclRequestProto)(nil),  // 0: hadoop.common.RefreshServiceAclRequestProto
	(*RefreshServiceAclResponseProto)(nil), // 1: hadoop.common.RefreshServiceAclResponseProto
}
var file_RefreshAuthorizationPolicyProtocol_proto_depIdxs = []int32{
	0, // 0: hadoop.common.RefreshAuthorizationPolicyProtocolService.refreshServiceAcl:input_type -> hadoop.common.RefreshServiceAclRequestProto
	1, // 1: hadoop.common.RefreshAuthorizationPolicyProtocolService.refreshServiceAcl:output_type -> hadoop.common.RefreshServiceAclResponseProto
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_RefreshAuthorizationPolicyProtocol_proto_init() }
func file_RefreshAuthorizationPolicyProtocol_proto_init() {
	if File_RefreshAuthorizationPolicyProtocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_RefreshAuthorizationPolicyProtocol_proto_rawDesc), len(file_RefreshAuthorizationPolicyProtocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_RefreshAuthorizationPolicyProtocol_proto_goTypes,
		DependencyIndexes: file_RefreshAuthorizationPolicyProtocol_proto_depIdxs,
		MessageInfos:      file_RefreshAuthorizationPolicyProtocol_proto_msgTypes,
	}.Build()
	File_RefreshAuthorizationPolicyProtocol_proto = out.File
	file_RefreshAuthorizationPolicyProtocol_proto_goTypes = nil
	file_RefreshAuthorizationPolicyProtocol_proto_depIdxs = nil
}
