//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// These .proto interfaces are private and stable.
// Please see http://wiki.apache.org/hadoop/Compatibility
// for what changes are allowed for a *stable* .proto interface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: TraceAdmin.proto

package hadoop_common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListSpanReceiversRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpanReceiversRequestProto) Reset() {
	*x = ListSpanReceiversRequestProto{}
	mi := &file_TraceAdmin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpanReceiversRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpanReceiversRequestProto) ProtoMessage() {}

func (x *ListSpanReceiversRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_TraceAdmin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpanReceiversRequestProto.ProtoReflect.Descriptor instead.
func (*ListSpanReceiversRequestProto) Descriptor() ([]byte, []int) {
	return file_TraceAdmin_proto_rawDescGZIP(), []int{0}
}

type SpanReceiverListInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	ClassName     *string                `protobuf:"bytes,2,req,name=className" json:"className,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanReceiverListInfo) Reset() {
	*x = SpanReceiverListInfo{}
	mi := &file_TraceAdmin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanReceiverListInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanReceiverListInfo) ProtoMessage() {}

func (x *SpanReceiverListInfo) ProtoReflect() protoreflect.Message {
	mi := &file_TraceAdmin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanReceiverListInfo.ProtoReflect.Descriptor instead.
func (*SpanReceiverListInfo) Descriptor() ([]byte, []int) {
	return file_TraceAdmin_proto_rawDescGZIP(), []int{1}
}

func (x *SpanReceiverListInfo) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *SpanReceiverListInfo) GetClassName() string {
	if x != nil && x.ClassName != nil {
		return *x.ClassName
	}
	return ""
}

type ListSpanReceiversResponseProto struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Descriptions  []*SpanReceiverListInfo `protobuf:"bytes,1,rep,name=descriptions" json:"descriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpanReceiversResponseProto) Reset() {
	*x = ListSpanReceiversResponseProto{}
	mi := &file_TraceAdmin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpanReceiversResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpanReceiversResponseProto) ProtoMessage() {}

func (x *ListSpanReceiversResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_TraceAdmin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpanReceiversResponseProto.ProtoReflect.Descriptor instead.
func (*ListSpanReceiversResponseProto) Descriptor() ([]byte, []int) {
	return file_TraceAdmin_proto_rawDescGZIP(), []int{2}
}

func (x *ListSpanReceiversResponseProto) GetDescriptions() []*SpanReceiverListInfo {
	if x != nil {
		return x.Descriptions
	}
	return nil
}

type ConfigPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPair) Reset() {
	*x = ConfigPair{}
	mi := &file_TraceAdmin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPair) ProtoMessage() {}

func (x *ConfigPair) ProtoReflect() protoreflect.Message {
	mi := &file_TraceAdmin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPair.ProtoReflect.Descriptor instead.
func (*ConfigPair) Descriptor() ([]byte, []int) {
	return file_TraceAdmin_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigPair) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *ConfigPair) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type AddSpanReceiverRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     *string                `protobuf:"bytes,1,req,name=className" json:"className,omitempty"`
	Config        []*ConfigPair          `protobuf:"bytes,2,rep,name=config" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSpanReceiverRequestProto) Reset() {
	*x = AddSpanReceiverRequestProto{}
	mi := &file_TraceAdmin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSpanReceiverRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSpanReceiverRequestProto) ProtoMessage() {}

func (x *AddSpanReceiverRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_TraceAdmin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSpanReceiverRequestProto.ProtoReflect.Descriptor instead.
func (*AddSpanReceiverRequestProto) Descriptor() ([]byte, []int) {
	return file_TraceAdmin_proto_rawDescGZIP(), []int{4}
}

func (x *AddSpanReceiverRequestProto) GetClassName() string {
	if x != nil && x.ClassName != nil {
		return *x.ClassName
	}
	return ""
}

func (x *AddSpanReceiverRequestProto) GetConfig() []*ConfigPair {
	if x != nil {
		return x.Config
	}
	return nil
}

type AddSpanReceiverResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSpanReceiverResponseProto) Reset() {
	*x = AddSpanReceiverResponseProto{}
	mi := &file_TraceAdmin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSpanReceiverResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSpanReceiverResponseProto) ProtoMessage() {}

func (x *AddSpanReceiverResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_TraceAdmin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSpanReceiverResponseProto.ProtoReflect.Descriptor instead.
func (*AddSpanReceiverResponseProto) Descriptor() ([]byte, []int) {
	return file_TraceAdmin_proto_rawDescGZIP(), []int{5}
}

func (x *AddSpanReceiverResponseProto) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

type RemoveSpanReceiverRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSpanReceiverRequestProto) Reset() {
	*x = RemoveSpanReceiverRequestProto{}
	mi := &file_TraceAdmin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSpanReceiverRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSpanReceiverRequestProto) ProtoMessage() {}

func (x *RemoveSpanReceiverRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_TraceAdmin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSpanReceiverRequestProto.ProtoReflect.Descriptor instead.
func (*RemoveSpanReceiverRequestProto) Descriptor() ([]byte, []int) {
	return file_TraceAdmin_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveSpanReceiverRequestProto) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

type RemoveSpanReceiverResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSpanReceiverResponseProto) Reset() {
	*x = RemoveSpanReceiverResponseProto{}
	mi := &file_TraceAdmin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSpanReceiverResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSpanReceiverResponseProto) ProtoMessage() {}

func (x *RemoveSpanReceiverResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_TraceAdmin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSpanReceiverResponseProto.ProtoReflect.Descriptor instead.
func (*RemoveSpanReceiverResponseProto) Descriptor() ([]byte, []int) {
	return file_TraceAdmin_proto_rawDescGZIP(), []int{7}
}

var File_TraceAdmin_proto protoreflect.FileDescriptor

const file_TraceAdmin_proto_rawDesc = "" +
	"\n" +
	"\x10TraceAdmin.proto\x12\rhadoop.common\"\x1f\n" +
	"\x1dListSpanReceiversRequestProto\"D\n" +
	"\x14SpanReceiverListInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x03R\x02id\x12\x1c\n" +
	"\tclassName\x18\x02 \x02(\tR\tclassName\"i\n" +
	"\x1eListSpanReceiversResponseProto\x12G\n" +
	"\fdescriptions\x18\x01 \x03(\v2#.hadoop.common.SpanReceiverListInfoR\fdescriptions\"4\n" +
	"\n" +
	"ConfigPair\x12\x10\n" +
	"\x03key\x18\x01 \x02(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x02(\tR\x05value\"n\n" +
	"\x1bAddSpanReceiverRequestProto\x12\x1c\n" +
	"\tclassName\x18\x01 \x02(\tR\tclassName\x121\n" +
	"\x06config\x18\x02 \x03(\v2\x19.hadoop.common.ConfigPairR\x06config\".\n" +
	"\x1cAddSpanReceiverResponseProto\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x03R\x02id\"0\n" +
	"\x1eRemoveSpanReceiverRequestProto\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x03R\x02id\"!\n" +
	"\x1fRemoveSpanReceiverResponseProto2\xe6\x02\n" +
	"\x11TraceAdminService\x12p\n" +
	"\x11listSpanReceivers\x12,.hadoop.common.ListSpanReceiversRequestProto\x1a-.hadoop.common.ListSpanReceiversResponseProto\x12j\n" +
	"\x0faddSpanReceiver\x12*.hadoop.common.AddSpanReceiverRequestProto\x1a+.hadoop.common.AddSpanReceiverResponseProto\x12s\n" +
	"\x12removeSpanReceiver\x12-.hadoop.common.RemoveSpanReceiverRequestProto\x1a..hadoop.common.RemoveSpanReceiverResponseProtoBm\n" +
	"\x19org.apache.hadoop.tracingB\fTraceAdminPBZ<github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_common\x88\x01\x01\xa0\x01\x01"

var (
	file_TraceAdmin_proto_rawDescOnce sync.Once
	file_TraceAdmin_proto_rawDescData []byte
)

func file_TraceAdmin_proto_rawDescGZIP() []byte {
	file_TraceAdmin_proto_rawDescOnce.Do(func() {
		file_TraceAdmin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TraceAdmin_proto_rawDesc), len(file_TraceAdmin_proto_rawDesc)))
	})
	return file_TraceAdmin_proto_rawDescData
}

var file_TraceAdmin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_TraceAdmin_proto_goTypes = []any{
	(*ListSpanReceiversRequestProto)(nil),   // 0: hadoop.common.ListSpanReceiversRequestProto
	(*SpanReceiverListInfo)(nil),            // 1: hadoop.common.SpanReceiverListInfo
	(*ListSpanReceiversResponseProto)(nil),  // 2: hadoop.common.ListSpanReceiversResponseProto
	(*ConfigPair)(nil),                      // 3: hadoop.common.ConfigPair
	(*AddSpanReceiverRequestProto)(nil),     // 4: hadoop.common.AddSpanReceiverRequestProto
	(*AddSpanReceiverResponseProto)(nil),    // 5: hadoop.common.AddSpanReceiverResponseProto
	(*RemoveSpanReceiverRequestProto)(nil),  // 6: hadoop.common.RemoveSpanReceiverRequestProto
	(*RemoveSpanReceiverResponseProto)(nil), // 7: hadoop.common.RemoveSpanReceiverResponseProto
}
var file_TraceAdmin_proto_depIdxs = []int32{
	1, // 0: hadoop.common.ListSpanReceiversResponseProto.descriptions:type_name -> hadoop.common.SpanReceiverListInfo
	3, // 1: hadoop.common.AddSpanReceiverRequestProto.config:type_name -> hadoop.common.ConfigPair
	0, // 2: hadoop.common.TraceAdminService.listSpanReceivers:input_type -> hadoop.common.ListSpanReceiversRequestProto
	4, // 3: hadoop.common.TraceAdminService.addSpanReceiver:input_type -> hadoop.common.AddSpanReceiverRequestProto
	6, // 4: hadoop.common.TraceAdminService.removeSpanReceiver:input_type -> hadoop.common.RemoveSpanReceiverRequestProto
	2, // 5: hadoop.common.TraceAdminService.listSpanReceivers:output_type -> hadoop.common.ListSpanReceiversResponseProto
	5, // 6: hadoop.common.TraceAdminService.addSpanReceiver:output_type -> hadoop.common.AddSpanReceiverResponseProto
	7, // 7: hadoop.common.TraceAdminService.removeSpanReceiver:output_type -> hadoop.common.RemoveSpanReceiverResponseProto
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_TraceAdmin_proto_init() }
func file_TraceAdmin_proto_init() {
	if File_TraceAdmin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TraceAdmin_proto_rawDesc), len(file_TraceAdmin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_TraceAdmin_proto_goTypes,
		DependencyIndexes: file_TraceAdmin_proto_depIdxs,
		MessageInfos:      file_TraceAdmin_proto_msgTypes,
	}.Build()
	File_TraceAdmin_proto = out.File
	file_TraceAdmin_proto_goTypes = nil
	file_TraceAdmin_proto_depIdxs = nil
}
