//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// These .proto interfaces are private and stable.
// Please see http://wiki.apache.org/hadoop/Compatibility
// for what changes are allowed for a *stable* .proto interface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: ZKFCProtocol.proto

package hadoop_common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CedeActiveRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MillisToCede  *uint32                `protobuf:"varint,1,req,name=millisToCede" json:"millisToCede,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CedeActiveRequestProto) Reset() {
	*x = CedeActiveRequestProto{}
	mi := &file_ZKFCProtocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CedeActiveRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CedeActiveRequestProto) ProtoMessage() {}

func (x *CedeActiveRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_ZKFCProtocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CedeActiveRequestProto.ProtoReflect.Descriptor instead.
func (*CedeActiveRequestProto) Descriptor() ([]byte, []int) {
	return file_ZKFCProtocol_proto_rawDescGZIP(), []int{0}
}

func (x *CedeActiveRequestProto) GetMillisToCede() uint32 {
	if x != nil && x.MillisToCede != nil {
		return *x.MillisToCede
	}
	return 0
}

type CedeActiveResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CedeActiveResponseProto) Reset() {
	*x = CedeActiveResponseProto{}
	mi := &file_ZKFCProtocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CedeActiveResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CedeActiveResponseProto) ProtoMessage() {}

func (x *CedeActiveResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_ZKFCProtocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CedeActiveResponseProto.ProtoReflect.Descriptor instead.
func (*CedeActiveResponseProto) Descriptor() ([]byte, []int) {
	return file_ZKFCProtocol_proto_rawDescGZIP(), []int{1}
}

type GracefulFailoverRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GracefulFailoverRequestProto) Reset() {
	*x = GracefulFailoverRequestProto{}
	mi := &file_ZKFCProtocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GracefulFailoverRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GracefulFailoverRequestProto) ProtoMessage() {}

func (x *GracefulFailoverRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_ZKFCProtocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GracefulFailoverRequestProto.ProtoReflect.Descriptor instead.
func (*GracefulFailoverRequestProto) Descriptor() ([]byte, []int) {
	return file_ZKFCProtocol_proto_rawDescGZIP(), []int{2}
}

type GracefulFailoverResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GracefulFailoverResponseProto) Reset() {
	*x = GracefulFailoverResponseProto{}
	mi := &file_ZKFCProtocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GracefulFailoverResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GracefulFailoverResponseProto) ProtoMessage() {}

func (x *GracefulFailoverResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_ZKFCProtocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GracefulFailoverResponseProto.ProtoReflect.Descriptor instead.
func (*GracefulFailoverResponseProto) Descriptor() ([]byte, []int) {
	return file_ZKFCProtocol_proto_rawDescGZIP(), []int{3}
}

var File_ZKFCProtocol_proto protoreflect.FileDescriptor

const file_ZKFCProtocol_proto_rawDesc = "" +
	"\n" +
	"\x12ZKFCProtocol.proto\x12\rhadoop.common\"<\n" +
	"\x16CedeActiveRequestProto\x12\"\n" +
	"\fmillisToCede\x18\x01 \x02(\rR\fmillisToCede\"\x19\n" +
	"\x17CedeActiveResponseProto\"\x1e\n" +
	"\x1cGracefulFailoverRequestProto\"\x1f\n" +
	"\x1dGracefulFailoverResponseProto2\xe1\x01\n" +
	"\x13ZKFCProtocolService\x12[\n" +
	"\n" +
	"cedeActive\x12%.hadoop.common.CedeActiveRequestProto\x1a&.hadoop.common.CedeActiveResponseProto\x12m\n" +
	"\x10gracefulFailover\x12+.hadoop.common.GracefulFailoverRequestProto\x1a,.hadoop.common.GracefulFailoverResponseProtoBt\n" +
	"\x1aorg.apache.hadoop.ha.protoB\x12ZKFCProtocolProtosZ<github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_common\x88\x01\x01\xa0\x01\x01"

var (
	file_ZKFCProtocol_proto_rawDescOnce sync.Once
	file_ZKFCProtocol_proto_rawDescData []byte
)

func file_ZKFCProtocol_proto_rawDescGZIP() []byte {
	file_ZKFCProtocol_proto_rawDescOnce.Do(func() {
		file_ZKFCProtocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ZKFCProtocol_proto_rawDesc), len(file_ZKFCProtocol_proto_rawDesc)))
	})
	return file_ZKFCProtocol_proto_rawDescData
}

var file_ZKFCProtocol_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ZKFCProtocol_proto_goTypes = []any{
	(*CedeActiveRequestProto)(nil),        // 0: hadoop.common.CedeActiveRequestProto
	(*CedeActiveResponseProto)(nil),       // 1: hadoop.common.CedeActiveResponseProto
	(*GracefulFailoverRequestProto)(nil),  // 2: hadoop.common.GracefulFailoverRequestProto
	(*GracefulFailoverResponseProto)(nil), // 3: hadoop.common.GracefulFailoverResponseProto
}
var file_ZKFCProtocol_proto_depIdxs = []int32{
	0, // 0: hadoop.common.ZKFCProtocolService.cedeActive:input_type -> hadoop.common.CedeActiveRequestProto
	2, // 1: hadoop.common.ZKFCProtocolService.gracefulFailover:input_type -> hadoop.common.GracefulFailoverRequestProto
	1, // 2: hadoop.common.ZKFCProtocolService.cedeActive:output_type -> hadoop.common.CedeActiveResponseProto
	3, // 3: hadoop.common.ZKFCProtocolService.gracefulFailover:output_type -> hadoop.common.GracefulFailoverResponseProto
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ZKFCProtocol_proto_init() }
func file_ZKFCProtocol_proto_init() {
	if File_ZKFCProtocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ZKFCProtocol_proto_rawDesc), len(file_ZKFCProtocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ZKFCProtocol_proto_goTypes,
		DependencyIndexes: file_ZKFCProtocol_proto_depIdxs,
		MessageInfos:      file_ZKFCProtocol_proto_msgTypes,
	}.Build()
	File_ZKFCProtocol_proto = out.File
	file_ZKFCProtocol_proto_goTypes = nil
	file_ZKFCProtocol_proto_depIdxs = nil
}
