//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: AliasMapProtocol.proto

package hadoop_hdfs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyValueProto struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Key           *BlockProto                   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value         *ProvidedStorageLocationProto `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValueProto) Reset() {
	*x = KeyValueProto{}
	mi := &file_AliasMapProtocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueProto) ProtoMessage() {}

func (x *KeyValueProto) ProtoReflect() protoreflect.Message {
	mi := &file_AliasMapProtocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueProto.ProtoReflect.Descriptor instead.
func (*KeyValueProto) Descriptor() ([]byte, []int) {
	return file_AliasMapProtocol_proto_rawDescGZIP(), []int{0}
}

func (x *KeyValueProto) GetKey() *BlockProto {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValueProto) GetValue() *ProvidedStorageLocationProto {
	if x != nil {
		return x.Value
	}
	return nil
}

type WriteRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyValuePair  *KeyValueProto         `protobuf:"bytes,1,req,name=keyValuePair" json:"keyValuePair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequestProto) Reset() {
	*x = WriteRequestProto{}
	mi := &file_AliasMapProtocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequestProto) ProtoMessage() {}

func (x *WriteRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_AliasMapProtocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequestProto.ProtoReflect.Descriptor instead.
func (*WriteRequestProto) Descriptor() ([]byte, []int) {
	return file_AliasMapProtocol_proto_rawDescGZIP(), []int{1}
}

func (x *WriteRequestProto) GetKeyValuePair() *KeyValueProto {
	if x != nil {
		return x.KeyValuePair
	}
	return nil
}

type WriteResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponseProto) Reset() {
	*x = WriteResponseProto{}
	mi := &file_AliasMapProtocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponseProto) ProtoMessage() {}

func (x *WriteResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_AliasMapProtocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponseProto.ProtoReflect.Descriptor instead.
func (*WriteResponseProto) Descriptor() ([]byte, []int) {
	return file_AliasMapProtocol_proto_rawDescGZIP(), []int{2}
}

type ReadRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *BlockProto            `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequestProto) Reset() {
	*x = ReadRequestProto{}
	mi := &file_AliasMapProtocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequestProto) ProtoMessage() {}

func (x *ReadRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_AliasMapProtocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequestProto.ProtoReflect.Descriptor instead.
func (*ReadRequestProto) Descriptor() ([]byte, []int) {
	return file_AliasMapProtocol_proto_rawDescGZIP(), []int{3}
}

func (x *ReadRequestProto) GetKey() *BlockProto {
	if x != nil {
		return x.Key
	}
	return nil
}

type ReadResponseProto struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Value         *ProvidedStorageLocationProto `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponseProto) Reset() {
	*x = ReadResponseProto{}
	mi := &file_AliasMapProtocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponseProto) ProtoMessage() {}

func (x *ReadResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_AliasMapProtocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponseProto.ProtoReflect.Descriptor instead.
func (*ReadResponseProto) Descriptor() ([]byte, []int) {
	return file_AliasMapProtocol_proto_rawDescGZIP(), []int{4}
}

func (x *ReadResponseProto) GetValue() *ProvidedStorageLocationProto {
	if x != nil {
		return x.Value
	}
	return nil
}

type ListRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Marker        *BlockProto            `protobuf:"bytes,1,opt,name=marker" json:"marker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestProto) Reset() {
	*x = ListRequestProto{}
	mi := &file_AliasMapProtocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestProto) ProtoMessage() {}

func (x *ListRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_AliasMapProtocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestProto.ProtoReflect.Descriptor instead.
func (*ListRequestProto) Descriptor() ([]byte, []int) {
	return file_AliasMapProtocol_proto_rawDescGZIP(), []int{5}
}

func (x *ListRequestProto) GetMarker() *BlockProto {
	if x != nil {
		return x.Marker
	}
	return nil
}

type ListResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileRegions   []*KeyValueProto       `protobuf:"bytes,1,rep,name=fileRegions" json:"fileRegions,omitempty"`
	NextMarker    *BlockProto            `protobuf:"bytes,2,opt,name=nextMarker" json:"nextMarker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponseProto) Reset() {
	*x = ListResponseProto{}
	mi := &file_AliasMapProtocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponseProto) ProtoMessage() {}

func (x *ListResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_AliasMapProtocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponseProto.ProtoReflect.Descriptor instead.
func (*ListResponseProto) Descriptor() ([]byte, []int) {
	return file_AliasMapProtocol_proto_rawDescGZIP(), []int{6}
}

func (x *ListResponseProto) GetFileRegions() []*KeyValueProto {
	if x != nil {
		return x.FileRegions
	}
	return nil
}

func (x *ListResponseProto) GetNextMarker() *BlockProto {
	if x != nil {
		return x.NextMarker
	}
	return nil
}

type BlockPoolRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockPoolRequestProto) Reset() {
	*x = BlockPoolRequestProto{}
	mi := &file_AliasMapProtocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockPoolRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPoolRequestProto) ProtoMessage() {}

func (x *BlockPoolRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_AliasMapProtocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPoolRequestProto.ProtoReflect.Descriptor instead.
func (*BlockPoolRequestProto) Descriptor() ([]byte, []int) {
	return file_AliasMapProtocol_proto_rawDescGZIP(), []int{7}
}

type BlockPoolResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockPoolId   *string                `protobuf:"bytes,1,req,name=blockPoolId" json:"blockPoolId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockPoolResponseProto) Reset() {
	*x = BlockPoolResponseProto{}
	mi := &file_AliasMapProtocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockPoolResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPoolResponseProto) ProtoMessage() {}

func (x *BlockPoolResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_AliasMapProtocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPoolResponseProto.ProtoReflect.Descriptor instead.
func (*BlockPoolResponseProto) Descriptor() ([]byte, []int) {
	return file_AliasMapProtocol_proto_rawDescGZIP(), []int{8}
}

func (x *BlockPoolResponseProto) GetBlockPoolId() string {
	if x != nil && x.BlockPoolId != nil {
		return *x.BlockPoolId
	}
	return ""
}

var File_AliasMapProtocol_proto protoreflect.FileDescriptor

const file_AliasMapProtocol_proto_rawDesc = "" +
	"\n" +
	"\x16AliasMapProtocol.proto\x12\vhadoop.hdfs\x1a\n" +
	"hdfs.proto\"{\n" +
	"\rKeyValueProto\x12)\n" +
	"\x03key\x18\x01 \x01(\v2\x17.hadoop.hdfs.BlockProtoR\x03key\x12?\n" +
	"\x05value\x18\x02 \x01(\v2).hadoop.hdfs.ProvidedStorageLocationProtoR\x05value\"S\n" +
	"\x11WriteRequestProto\x12>\n" +
	"\fkeyValuePair\x18\x01 \x02(\v2\x1a.hadoop.hdfs.KeyValueProtoR\fkeyValuePair\"\x14\n" +
	"\x12WriteResponseProto\"=\n" +
	"\x10ReadRequestProto\x12)\n" +
	"\x03key\x18\x01 \x02(\v2\x17.hadoop.hdfs.BlockProtoR\x03key\"T\n" +
	"\x11ReadResponseProto\x12?\n" +
	"\x05value\x18\x01 \x01(\v2).hadoop.hdfs.ProvidedStorageLocationProtoR\x05value\"C\n" +
	"\x10ListRequestProto\x12/\n" +
	"\x06marker\x18\x01 \x01(\v2\x17.hadoop.hdfs.BlockProtoR\x06marker\"\x8a\x01\n" +
	"\x11ListResponseProto\x12<\n" +
	"\vfileRegions\x18\x01 \x03(\v2\x1a.hadoop.hdfs.KeyValueProtoR\vfileRegions\x127\n" +
	"\n" +
	"nextMarker\x18\x02 \x01(\v2\x17.hadoop.hdfs.BlockProtoR\n" +
	"nextMarker\"\x17\n" +
	"\x15BlockPoolRequestProto\":\n" +
	"\x16BlockPoolResponseProto\x12 \n" +
	"\vblockPoolId\x18\x01 \x02(\tR\vblockPoolId2\xcc\x02\n" +
	"\x17AliasMapProtocolService\x12H\n" +
	"\x05write\x12\x1e.hadoop.hdfs.WriteRequestProto\x1a\x1f.hadoop.hdfs.WriteResponseProto\x12E\n" +
	"\x04read\x12\x1d.hadoop.hdfs.ReadRequestProto\x1a\x1e.hadoop.hdfs.ReadResponseProto\x12E\n" +
	"\x04list\x12\x1d.hadoop.hdfs.ListRequestProto\x1a\x1e.hadoop.hdfs.ListResponseProto\x12Y\n" +
	"\x0egetBlockPoolId\x12\".hadoop.hdfs.BlockPoolRequestProto\x1a#.hadoop.hdfs.BlockPoolResponseProtoB\x81\x01\n" +
	"%org.apache.hadoop.hdfs.protocol.protoB\x16AliasMapProtocolProtosZ:github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs\x88\x01\x01\xa0\x01\x01"

var (
	file_AliasMapProtocol_proto_rawDescOnce sync.Once
	file_AliasMapProtocol_proto_rawDescData []byte
)

func file_AliasMapProtocol_proto_rawDescGZIP() []byte {
	file_AliasMapProtocol_proto_rawDescOnce.Do(func() {
		file_AliasMapProtocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AliasMapProtocol_proto_rawDesc), len(file_AliasMapProtocol_proto_rawDesc)))
	})
	return file_AliasMapProtocol_proto_rawDescData
}

var file_AliasMapProtocol_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_AliasMapProtocol_proto_goTypes = []any{
	(*KeyValueProto)(nil),                // 0: hadoop.hdfs.KeyValueProto
	(*WriteRequestProto)(nil),            // 1: hadoop.hdfs.WriteRequestProto
	(*WriteResponseProto)(nil),           // 2: hadoop.hdfs.WriteResponseProto
	(*ReadRequestProto)(nil),             // 3: hadoop.hdfs.ReadRequestProto
	(*ReadResponseProto)(nil),            // 4: hadoop.hdfs.ReadResponseProto
	(*ListRequestProto)(nil),             // 5: hadoop.hdfs.ListRequestProto
	(*ListResponseProto)(nil),            // 6: hadoop.hdfs.ListResponseProto
	(*BlockPoolRequestProto)(nil),        // 7: hadoop.hdfs.BlockPoolRequestProto
	(*BlockPoolResponseProto)(nil),       // 8: hadoop.hdfs.BlockPoolResponseProto
	(*BlockProto)(nil),                   // 9: hadoop.hdfs.BlockProto
	(*ProvidedStorageLocationProto)(nil), // 10: hadoop.hdfs.ProvidedStorageLocationProto
}
var file_AliasMapProtocol_proto_depIdxs = []int32{
	9,  // 0: hadoop.hdfs.KeyValueProto.key:type_name -> hadoop.hdfs.BlockProto
	10, // 1: hadoop.hdfs.KeyValueProto.value:type_name -> hadoop.hdfs.ProvidedStorageLocationProto
	0,  // 2: hadoop.hdfs.WriteRequestProto.keyValuePair:type_name -> hadoop.hdfs.KeyValueProto
	9,  // 3: hadoop.hdfs.ReadRequestProto.key:type_name -> hadoop.hdfs.BlockProto
	10, // 4: hadoop.hdfs.ReadResponseProto.value:type_name -> hadoop.hdfs.ProvidedStorageLocationProto
	9,  // 5: hadoop.hdfs.ListRequestProto.marker:type_name -> hadoop.hdfs.BlockProto
	0,  // 6: hadoop.hdfs.ListResponseProto.fileRegions:type_name -> hadoop.hdfs.KeyValueProto
	9,  // 7: hadoop.hdfs.ListResponseProto.nextMarker:type_name -> hadoop.hdfs.BlockProto
	1,  // 8: hadoop.hdfs.AliasMapProtocolService.write:input_type -> hadoop.hdfs.WriteRequestProto
	3,  // 9: hadoop.hdfs.AliasMapProtocolService.read:input_type -> hadoop.hdfs.ReadRequestProto
	5,  // 10: hadoop.hdfs.AliasMapProtocolService.list:input_type -> hadoop.hdfs.ListRequestProto
	7,  // 11: hadoop.hdfs.AliasMapProtocolService.getBlockPoolId:input_type -> hadoop.hdfs.BlockPoolRequestProto
	2,  // 12: hadoop.hdfs.AliasMapProtocolService.write:output_type -> hadoop.hdfs.WriteResponseProto
	4,  // 13: hadoop.hdfs.AliasMapProtocolService.read:output_type -> hadoop.hdfs.ReadResponseProto
	6,  // 14: hadoop.hdfs.AliasMapProtocolService.list:output_type -> hadoop.hdfs.ListResponseProto
	8,  // 15: hadoop.hdfs.AliasMapProtocolService.getBlockPoolId:output_type -> hadoop.hdfs.BlockPoolResponseProto
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_AliasMapProtocol_proto_init() }
func file_AliasMapProtocol_proto_init() {
	if File_AliasMapProtocol_proto != nil {
		return
	}
	file_hdfs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AliasMapProtocol_proto_rawDesc), len(file_AliasMapProtocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_AliasMapProtocol_proto_goTypes,
		DependencyIndexes: file_AliasMapProtocol_proto_depIdxs,
		MessageInfos:      file_AliasMapProtocol_proto_msgTypes,
	}.Build()
	File_AliasMapProtocol_proto = out.File
	file_AliasMapProtocol_proto_goTypes = nil
	file_AliasMapProtocol_proto_depIdxs = nil
}
