//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: editlog.proto

package hadoop_hdfs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AclEditLogProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           *string                `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	Entries       []*AclEntryProto       `protobuf:"bytes,2,rep,name=entries" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AclEditLogProto) Reset() {
	*x = AclEditLogProto{}
	mi := &file_editlog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AclEditLogProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AclEditLogProto) ProtoMessage() {}

func (x *AclEditLogProto) ProtoReflect() protoreflect.Message {
	mi := &file_editlog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AclEditLogProto.ProtoReflect.Descriptor instead.
func (*AclEditLogProto) Descriptor() ([]byte, []int) {
	return file_editlog_proto_rawDescGZIP(), []int{0}
}

func (x *AclEditLogProto) GetSrc() string {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return ""
}

func (x *AclEditLogProto) GetEntries() []*AclEntryProto {
	if x != nil {
		return x.Entries
	}
	return nil
}

type XAttrEditLogProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           *string                `protobuf:"bytes,1,opt,name=src" json:"src,omitempty"`
	XAttrs        []*XAttrProto          `protobuf:"bytes,2,rep,name=xAttrs" json:"xAttrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XAttrEditLogProto) Reset() {
	*x = XAttrEditLogProto{}
	mi := &file_editlog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XAttrEditLogProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XAttrEditLogProto) ProtoMessage() {}

func (x *XAttrEditLogProto) ProtoReflect() protoreflect.Message {
	mi := &file_editlog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XAttrEditLogProto.ProtoReflect.Descriptor instead.
func (*XAttrEditLogProto) Descriptor() ([]byte, []int) {
	return file_editlog_proto_rawDescGZIP(), []int{1}
}

func (x *XAttrEditLogProto) GetSrc() string {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return ""
}

func (x *XAttrEditLogProto) GetXAttrs() []*XAttrProto {
	if x != nil {
		return x.XAttrs
	}
	return nil
}

var File_editlog_proto protoreflect.FileDescriptor

const file_editlog_proto_rawDesc = "" +
	"\n" +
	"\reditlog.proto\x12\vhadoop.hdfs\x1a\tacl.proto\x1a\vxattr.proto\"Y\n" +
	"\x0fAclEditLogProto\x12\x10\n" +
	"\x03src\x18\x01 \x02(\tR\x03src\x124\n" +
	"\aentries\x18\x02 \x03(\v2\x1a.hadoop.hdfs.AclEntryProtoR\aentries\"V\n" +
	"\x11XAttrEditLogProto\x12\x10\n" +
	"\x03src\x18\x01 \x01(\tR\x03src\x12/\n" +
	"\x06xAttrs\x18\x02 \x03(\v2\x17.hadoop.hdfs.XAttrProtoR\x06xAttrsBu\n" +
	"%org.apache.hadoop.hdfs.protocol.protoB\rEditLogProtosZ:github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs\xa0\x01\x01"

var (
	file_editlog_proto_rawDescOnce sync.Once
	file_editlog_proto_rawDescData []byte
)

func file_editlog_proto_rawDescGZIP() []byte {
	file_editlog_proto_rawDescOnce.Do(func() {
		file_editlog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_editlog_proto_rawDesc), len(file_editlog_proto_rawDesc)))
	})
	return file_editlog_proto_rawDescData
}

var file_editlog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_editlog_proto_goTypes = []any{
	(*AclEditLogProto)(nil),   // 0: hadoop.hdfs.AclEditLogProto
	(*XAttrEditLogProto)(nil), // 1: hadoop.hdfs.XAttrEditLogProto
	(*AclEntryProto)(nil),     // 2: hadoop.hdfs.AclEntryProto
	(*XAttrProto)(nil),        // 3: hadoop.hdfs.XAttrProto
}
var file_editlog_proto_depIdxs = []int32{
	2, // 0: hadoop.hdfs.AclEditLogProto.entries:type_name -> hadoop.hdfs.AclEntryProto
	3, // 1: hadoop.hdfs.XAttrEditLogProto.xAttrs:type_name -> hadoop.hdfs.XAttrProto
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_editlog_proto_init() }
func file_editlog_proto_init() {
	if File_editlog_proto != nil {
		return
	}
	file_acl_proto_init()
	file_xattr_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_editlog_proto_rawDesc), len(file_editlog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_editlog_proto_goTypes,
		DependencyIndexes: file_editlog_proto_depIdxs,
		MessageInfos:      file_editlog_proto_msgTypes,
	}.Build()
	File_editlog_proto = out.File
	file_editlog_proto_goTypes = nil
	file_editlog_proto_depIdxs = nil
}
