//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: erasurecoding.proto

package hadoop_hdfs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetErasureCodingPolicyRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           *string                `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	EcPolicyName  *string                `protobuf:"bytes,2,opt,name=ecPolicyName" json:"ecPolicyName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetErasureCodingPolicyRequestProto) Reset() {
	*x = SetErasureCodingPolicyRequestProto{}
	mi := &file_erasurecoding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetErasureCodingPolicyRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetErasureCodingPolicyRequestProto) ProtoMessage() {}

func (x *SetErasureCodingPolicyRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetErasureCodingPolicyRequestProto.ProtoReflect.Descriptor instead.
func (*SetErasureCodingPolicyRequestProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{0}
}

func (x *SetErasureCodingPolicyRequestProto) GetSrc() string {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return ""
}

func (x *SetErasureCodingPolicyRequestProto) GetEcPolicyName() string {
	if x != nil && x.EcPolicyName != nil {
		return *x.EcPolicyName
	}
	return ""
}

type SetErasureCodingPolicyResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetErasureCodingPolicyResponseProto) Reset() {
	*x = SetErasureCodingPolicyResponseProto{}
	mi := &file_erasurecoding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetErasureCodingPolicyResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetErasureCodingPolicyResponseProto) ProtoMessage() {}

func (x *SetErasureCodingPolicyResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetErasureCodingPolicyResponseProto.ProtoReflect.Descriptor instead.
func (*SetErasureCodingPolicyResponseProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{1}
}

type GetErasureCodingPoliciesRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetErasureCodingPoliciesRequestProto) Reset() {
	*x = GetErasureCodingPoliciesRequestProto{}
	mi := &file_erasurecoding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetErasureCodingPoliciesRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetErasureCodingPoliciesRequestProto) ProtoMessage() {}

func (x *GetErasureCodingPoliciesRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetErasureCodingPoliciesRequestProto.ProtoReflect.Descriptor instead.
func (*GetErasureCodingPoliciesRequestProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{2}
}

type GetErasureCodingPoliciesResponseProto struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	EcPolicies    []*ErasureCodingPolicyProto `protobuf:"bytes,1,rep,name=ecPolicies" json:"ecPolicies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetErasureCodingPoliciesResponseProto) Reset() {
	*x = GetErasureCodingPoliciesResponseProto{}
	mi := &file_erasurecoding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetErasureCodingPoliciesResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetErasureCodingPoliciesResponseProto) ProtoMessage() {}

func (x *GetErasureCodingPoliciesResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetErasureCodingPoliciesResponseProto.ProtoReflect.Descriptor instead.
func (*GetErasureCodingPoliciesResponseProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{3}
}

func (x *GetErasureCodingPoliciesResponseProto) GetEcPolicies() []*ErasureCodingPolicyProto {
	if x != nil {
		return x.EcPolicies
	}
	return nil
}

type GetErasureCodingCodecsRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetErasureCodingCodecsRequestProto) Reset() {
	*x = GetErasureCodingCodecsRequestProto{}
	mi := &file_erasurecoding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetErasureCodingCodecsRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetErasureCodingCodecsRequestProto) ProtoMessage() {}

func (x *GetErasureCodingCodecsRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetErasureCodingCodecsRequestProto.ProtoReflect.Descriptor instead.
func (*GetErasureCodingCodecsRequestProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{4}
}

type GetErasureCodingCodecsResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codec         []*CodecProto          `protobuf:"bytes,1,rep,name=codec" json:"codec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetErasureCodingCodecsResponseProto) Reset() {
	*x = GetErasureCodingCodecsResponseProto{}
	mi := &file_erasurecoding_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetErasureCodingCodecsResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetErasureCodingCodecsResponseProto) ProtoMessage() {}

func (x *GetErasureCodingCodecsResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetErasureCodingCodecsResponseProto.ProtoReflect.Descriptor instead.
func (*GetErasureCodingCodecsResponseProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{5}
}

func (x *GetErasureCodingCodecsResponseProto) GetCodec() []*CodecProto {
	if x != nil {
		return x.Codec
	}
	return nil
}

type GetErasureCodingPolicyRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           *string                `protobuf:"bytes,1,req,name=src" json:"src,omitempty"` // path to get the policy info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetErasureCodingPolicyRequestProto) Reset() {
	*x = GetErasureCodingPolicyRequestProto{}
	mi := &file_erasurecoding_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetErasureCodingPolicyRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetErasureCodingPolicyRequestProto) ProtoMessage() {}

func (x *GetErasureCodingPolicyRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetErasureCodingPolicyRequestProto.ProtoReflect.Descriptor instead.
func (*GetErasureCodingPolicyRequestProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{6}
}

func (x *GetErasureCodingPolicyRequestProto) GetSrc() string {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return ""
}

type GetErasureCodingPolicyResponseProto struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	EcPolicy      *ErasureCodingPolicyProto `protobuf:"bytes,1,opt,name=ecPolicy" json:"ecPolicy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetErasureCodingPolicyResponseProto) Reset() {
	*x = GetErasureCodingPolicyResponseProto{}
	mi := &file_erasurecoding_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetErasureCodingPolicyResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetErasureCodingPolicyResponseProto) ProtoMessage() {}

func (x *GetErasureCodingPolicyResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetErasureCodingPolicyResponseProto.ProtoReflect.Descriptor instead.
func (*GetErasureCodingPolicyResponseProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{7}
}

func (x *GetErasureCodingPolicyResponseProto) GetEcPolicy() *ErasureCodingPolicyProto {
	if x != nil {
		return x.EcPolicy
	}
	return nil
}

type AddErasureCodingPoliciesRequestProto struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	EcPolicies    []*ErasureCodingPolicyProto `protobuf:"bytes,1,rep,name=ecPolicies" json:"ecPolicies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddErasureCodingPoliciesRequestProto) Reset() {
	*x = AddErasureCodingPoliciesRequestProto{}
	mi := &file_erasurecoding_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddErasureCodingPoliciesRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddErasureCodingPoliciesRequestProto) ProtoMessage() {}

func (x *AddErasureCodingPoliciesRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddErasureCodingPoliciesRequestProto.ProtoReflect.Descriptor instead.
func (*AddErasureCodingPoliciesRequestProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{8}
}

func (x *AddErasureCodingPoliciesRequestProto) GetEcPolicies() []*ErasureCodingPolicyProto {
	if x != nil {
		return x.EcPolicies
	}
	return nil
}

type AddErasureCodingPoliciesResponseProto struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Responses     []*AddErasureCodingPolicyResponseProto `protobuf:"bytes,1,rep,name=responses" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddErasureCodingPoliciesResponseProto) Reset() {
	*x = AddErasureCodingPoliciesResponseProto{}
	mi := &file_erasurecoding_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddErasureCodingPoliciesResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddErasureCodingPoliciesResponseProto) ProtoMessage() {}

func (x *AddErasureCodingPoliciesResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddErasureCodingPoliciesResponseProto.ProtoReflect.Descriptor instead.
func (*AddErasureCodingPoliciesResponseProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{9}
}

func (x *AddErasureCodingPoliciesResponseProto) GetResponses() []*AddErasureCodingPolicyResponseProto {
	if x != nil {
		return x.Responses
	}
	return nil
}

type RemoveErasureCodingPolicyRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EcPolicyName  *string                `protobuf:"bytes,1,req,name=ecPolicyName" json:"ecPolicyName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveErasureCodingPolicyRequestProto) Reset() {
	*x = RemoveErasureCodingPolicyRequestProto{}
	mi := &file_erasurecoding_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveErasureCodingPolicyRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveErasureCodingPolicyRequestProto) ProtoMessage() {}

func (x *RemoveErasureCodingPolicyRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveErasureCodingPolicyRequestProto.ProtoReflect.Descriptor instead.
func (*RemoveErasureCodingPolicyRequestProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveErasureCodingPolicyRequestProto) GetEcPolicyName() string {
	if x != nil && x.EcPolicyName != nil {
		return *x.EcPolicyName
	}
	return ""
}

type RemoveErasureCodingPolicyResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveErasureCodingPolicyResponseProto) Reset() {
	*x = RemoveErasureCodingPolicyResponseProto{}
	mi := &file_erasurecoding_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveErasureCodingPolicyResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveErasureCodingPolicyResponseProto) ProtoMessage() {}

func (x *RemoveErasureCodingPolicyResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveErasureCodingPolicyResponseProto.ProtoReflect.Descriptor instead.
func (*RemoveErasureCodingPolicyResponseProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{11}
}

type EnableErasureCodingPolicyRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EcPolicyName  *string                `protobuf:"bytes,1,req,name=ecPolicyName" json:"ecPolicyName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableErasureCodingPolicyRequestProto) Reset() {
	*x = EnableErasureCodingPolicyRequestProto{}
	mi := &file_erasurecoding_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableErasureCodingPolicyRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableErasureCodingPolicyRequestProto) ProtoMessage() {}

func (x *EnableErasureCodingPolicyRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableErasureCodingPolicyRequestProto.ProtoReflect.Descriptor instead.
func (*EnableErasureCodingPolicyRequestProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{12}
}

func (x *EnableErasureCodingPolicyRequestProto) GetEcPolicyName() string {
	if x != nil && x.EcPolicyName != nil {
		return *x.EcPolicyName
	}
	return ""
}

type EnableErasureCodingPolicyResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableErasureCodingPolicyResponseProto) Reset() {
	*x = EnableErasureCodingPolicyResponseProto{}
	mi := &file_erasurecoding_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableErasureCodingPolicyResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableErasureCodingPolicyResponseProto) ProtoMessage() {}

func (x *EnableErasureCodingPolicyResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableErasureCodingPolicyResponseProto.ProtoReflect.Descriptor instead.
func (*EnableErasureCodingPolicyResponseProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{13}
}

type DisableErasureCodingPolicyRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EcPolicyName  *string                `protobuf:"bytes,1,req,name=ecPolicyName" json:"ecPolicyName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableErasureCodingPolicyRequestProto) Reset() {
	*x = DisableErasureCodingPolicyRequestProto{}
	mi := &file_erasurecoding_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableErasureCodingPolicyRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableErasureCodingPolicyRequestProto) ProtoMessage() {}

func (x *DisableErasureCodingPolicyRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableErasureCodingPolicyRequestProto.ProtoReflect.Descriptor instead.
func (*DisableErasureCodingPolicyRequestProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{14}
}

func (x *DisableErasureCodingPolicyRequestProto) GetEcPolicyName() string {
	if x != nil && x.EcPolicyName != nil {
		return *x.EcPolicyName
	}
	return ""
}

type DisableErasureCodingPolicyResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableErasureCodingPolicyResponseProto) Reset() {
	*x = DisableErasureCodingPolicyResponseProto{}
	mi := &file_erasurecoding_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableErasureCodingPolicyResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableErasureCodingPolicyResponseProto) ProtoMessage() {}

func (x *DisableErasureCodingPolicyResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableErasureCodingPolicyResponseProto.ProtoReflect.Descriptor instead.
func (*DisableErasureCodingPolicyResponseProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{15}
}

type UnsetErasureCodingPolicyRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           *string                `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsetErasureCodingPolicyRequestProto) Reset() {
	*x = UnsetErasureCodingPolicyRequestProto{}
	mi := &file_erasurecoding_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsetErasureCodingPolicyRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsetErasureCodingPolicyRequestProto) ProtoMessage() {}

func (x *UnsetErasureCodingPolicyRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsetErasureCodingPolicyRequestProto.ProtoReflect.Descriptor instead.
func (*UnsetErasureCodingPolicyRequestProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{16}
}

func (x *UnsetErasureCodingPolicyRequestProto) GetSrc() string {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return ""
}

type UnsetErasureCodingPolicyResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsetErasureCodingPolicyResponseProto) Reset() {
	*x = UnsetErasureCodingPolicyResponseProto{}
	mi := &file_erasurecoding_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsetErasureCodingPolicyResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsetErasureCodingPolicyResponseProto) ProtoMessage() {}

func (x *UnsetErasureCodingPolicyResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsetErasureCodingPolicyResponseProto.ProtoReflect.Descriptor instead.
func (*UnsetErasureCodingPolicyResponseProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{17}
}

type GetECTopologyResultForPoliciesRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []string               `protobuf:"bytes,1,rep,name=policies" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetECTopologyResultForPoliciesRequestProto) Reset() {
	*x = GetECTopologyResultForPoliciesRequestProto{}
	mi := &file_erasurecoding_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetECTopologyResultForPoliciesRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetECTopologyResultForPoliciesRequestProto) ProtoMessage() {}

func (x *GetECTopologyResultForPoliciesRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetECTopologyResultForPoliciesRequestProto.ProtoReflect.Descriptor instead.
func (*GetECTopologyResultForPoliciesRequestProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{18}
}

func (x *GetECTopologyResultForPoliciesRequestProto) GetPolicies() []string {
	if x != nil {
		return x.Policies
	}
	return nil
}

type GetECTopologyResultForPoliciesResponseProto struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Response      *ECTopologyVerifierResultProto `protobuf:"bytes,1,req,name=response" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetECTopologyResultForPoliciesResponseProto) Reset() {
	*x = GetECTopologyResultForPoliciesResponseProto{}
	mi := &file_erasurecoding_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetECTopologyResultForPoliciesResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetECTopologyResultForPoliciesResponseProto) ProtoMessage() {}

func (x *GetECTopologyResultForPoliciesResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetECTopologyResultForPoliciesResponseProto.ProtoReflect.Descriptor instead.
func (*GetECTopologyResultForPoliciesResponseProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{19}
}

func (x *GetECTopologyResultForPoliciesResponseProto) GetResponse() *ECTopologyVerifierResultProto {
	if x != nil {
		return x.Response
	}
	return nil
}

// *
// Block erasure coding reconstruction info
type BlockECReconstructionInfoProto struct {
	state              protoimpl.MessageState    `protogen:"open.v1"`
	Block              *ExtendedBlockProto       `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	SourceDnInfos      *DatanodeInfosProto       `protobuf:"bytes,2,req,name=sourceDnInfos" json:"sourceDnInfos,omitempty"`
	TargetDnInfos      *DatanodeInfosProto       `protobuf:"bytes,3,req,name=targetDnInfos" json:"targetDnInfos,omitempty"`
	TargetStorageUuids *StorageUuidsProto        `protobuf:"bytes,4,req,name=targetStorageUuids" json:"targetStorageUuids,omitempty"`
	TargetStorageTypes *StorageTypesProto        `protobuf:"bytes,5,req,name=targetStorageTypes" json:"targetStorageTypes,omitempty"`
	LiveBlockIndices   []byte                    `protobuf:"bytes,6,req,name=liveBlockIndices" json:"liveBlockIndices,omitempty"`
	EcPolicy           *ErasureCodingPolicyProto `protobuf:"bytes,7,req,name=ecPolicy" json:"ecPolicy,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BlockECReconstructionInfoProto) Reset() {
	*x = BlockECReconstructionInfoProto{}
	mi := &file_erasurecoding_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockECReconstructionInfoProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockECReconstructionInfoProto) ProtoMessage() {}

func (x *BlockECReconstructionInfoProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockECReconstructionInfoProto.ProtoReflect.Descriptor instead.
func (*BlockECReconstructionInfoProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{20}
}

func (x *BlockECReconstructionInfoProto) GetBlock() *ExtendedBlockProto {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *BlockECReconstructionInfoProto) GetSourceDnInfos() *DatanodeInfosProto {
	if x != nil {
		return x.SourceDnInfos
	}
	return nil
}

func (x *BlockECReconstructionInfoProto) GetTargetDnInfos() *DatanodeInfosProto {
	if x != nil {
		return x.TargetDnInfos
	}
	return nil
}

func (x *BlockECReconstructionInfoProto) GetTargetStorageUuids() *StorageUuidsProto {
	if x != nil {
		return x.TargetStorageUuids
	}
	return nil
}

func (x *BlockECReconstructionInfoProto) GetTargetStorageTypes() *StorageTypesProto {
	if x != nil {
		return x.TargetStorageTypes
	}
	return nil
}

func (x *BlockECReconstructionInfoProto) GetLiveBlockIndices() []byte {
	if x != nil {
		return x.LiveBlockIndices
	}
	return nil
}

func (x *BlockECReconstructionInfoProto) GetEcPolicy() *ErasureCodingPolicyProto {
	if x != nil {
		return x.EcPolicy
	}
	return nil
}

// *
// Codec and it's corresponding coders
type CodecProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codec         *string                `protobuf:"bytes,1,req,name=codec" json:"codec,omitempty"`
	Coders        *string                `protobuf:"bytes,2,req,name=coders" json:"coders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodecProto) Reset() {
	*x = CodecProto{}
	mi := &file_erasurecoding_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodecProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodecProto) ProtoMessage() {}

func (x *CodecProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodecProto.ProtoReflect.Descriptor instead.
func (*CodecProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{21}
}

func (x *CodecProto) GetCodec() string {
	if x != nil && x.Codec != nil {
		return *x.Codec
	}
	return ""
}

func (x *CodecProto) GetCoders() string {
	if x != nil && x.Coders != nil {
		return *x.Coders
	}
	return ""
}

var File_erasurecoding_proto protoreflect.FileDescriptor

const file_erasurecoding_proto_rawDesc = "" +
	"\n" +
	"\x13erasurecoding.proto\x12\vhadoop.hdfs\x1a\n" +
	"hdfs.proto\"Z\n" +
	"\"SetErasureCodingPolicyRequestProto\x12\x10\n" +
	"\x03src\x18\x01 \x02(\tR\x03src\x12\"\n" +
	"\fecPolicyName\x18\x02 \x01(\tR\fecPolicyName\"%\n" +
	"#SetErasureCodingPolicyResponseProto\"&\n" +
	"$GetErasureCodingPoliciesRequestProto\"n\n" +
	"%GetErasureCodingPoliciesResponseProto\x12E\n" +
	"\n" +
	"ecPolicies\x18\x01 \x03(\v2%.hadoop.hdfs.ErasureCodingPolicyProtoR\n" +
	"ecPolicies\"$\n" +
	"\"GetErasureCodingCodecsRequestProto\"T\n" +
	"#GetErasureCodingCodecsResponseProto\x12-\n" +
	"\x05codec\x18\x01 \x03(\v2\x17.hadoop.hdfs.CodecProtoR\x05codec\"6\n" +
	"\"GetErasureCodingPolicyRequestProto\x12\x10\n" +
	"\x03src\x18\x01 \x02(\tR\x03src\"h\n" +
	"#GetErasureCodingPolicyResponseProto\x12A\n" +
	"\becPolicy\x18\x01 \x01(\v2%.hadoop.hdfs.ErasureCodingPolicyProtoR\becPolicy\"m\n" +
	"$AddErasureCodingPoliciesRequestProto\x12E\n" +
	"\n" +
	"ecPolicies\x18\x01 \x03(\v2%.hadoop.hdfs.ErasureCodingPolicyProtoR\n" +
	"ecPolicies\"w\n" +
	"%AddErasureCodingPoliciesResponseProto\x12N\n" +
	"\tresponses\x18\x01 \x03(\v20.hadoop.hdfs.AddErasureCodingPolicyResponseProtoR\tresponses\"K\n" +
	"%RemoveErasureCodingPolicyRequestProto\x12\"\n" +
	"\fecPolicyName\x18\x01 \x02(\tR\fecPolicyName\"(\n" +
	"&RemoveErasureCodingPolicyResponseProto\"K\n" +
	"%EnableErasureCodingPolicyRequestProto\x12\"\n" +
	"\fecPolicyName\x18\x01 \x02(\tR\fecPolicyName\"(\n" +
	"&EnableErasureCodingPolicyResponseProto\"L\n" +
	"&DisableErasureCodingPolicyRequestProto\x12\"\n" +
	"\fecPolicyName\x18\x01 \x02(\tR\fecPolicyName\")\n" +
	"'DisableErasureCodingPolicyResponseProto\"8\n" +
	"$UnsetErasureCodingPolicyRequestProto\x12\x10\n" +
	"\x03src\x18\x01 \x02(\tR\x03src\"'\n" +
	"%UnsetErasureCodingPolicyResponseProto\"H\n" +
	"*GetECTopologyResultForPoliciesRequestProto\x12\x1a\n" +
	"\bpolicies\x18\x01 \x03(\tR\bpolicies\"u\n" +
	"+GetECTopologyResultForPoliciesResponseProto\x12F\n" +
	"\bresponse\x18\x01 \x02(\v2*.hadoop.hdfs.ECTopologyVerifierResultProtoR\bresponse\"\xf4\x03\n" +
	"\x1eBlockECReconstructionInfoProto\x125\n" +
	"\x05block\x18\x01 \x02(\v2\x1f.hadoop.hdfs.ExtendedBlockProtoR\x05block\x12E\n" +
	"\rsourceDnInfos\x18\x02 \x02(\v2\x1f.hadoop.hdfs.DatanodeInfosProtoR\rsourceDnInfos\x12E\n" +
	"\rtargetDnInfos\x18\x03 \x02(\v2\x1f.hadoop.hdfs.DatanodeInfosProtoR\rtargetDnInfos\x12N\n" +
	"\x12targetStorageUuids\x18\x04 \x02(\v2\x1e.hadoop.hdfs.StorageUuidsProtoR\x12targetStorageUuids\x12N\n" +
	"\x12targetStorageTypes\x18\x05 \x02(\v2\x1e.hadoop.hdfs.StorageTypesProtoR\x12targetStorageTypes\x12*\n" +
	"\x10liveBlockIndices\x18\x06 \x02(\fR\x10liveBlockIndices\x12A\n" +
	"\becPolicy\x18\a \x02(\v2%.hadoop.hdfs.ErasureCodingPolicyProtoR\becPolicy\":\n" +
	"\n" +
	"CodecProto\x12\x14\n" +
	"\x05codec\x18\x01 \x02(\tR\x05codec\x12\x16\n" +
	"\x06coders\x18\x02 \x02(\tR\x06codersB{\n" +
	"%org.apache.hadoop.hdfs.protocol.protoB\x13ErasureCodingProtosZ:github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs\xa0\x01\x01"

var (
	file_erasurecoding_proto_rawDescOnce sync.Once
	file_erasurecoding_proto_rawDescData []byte
)

func file_erasurecoding_proto_rawDescGZIP() []byte {
	file_erasurecoding_proto_rawDescOnce.Do(func() {
		file_erasurecoding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_erasurecoding_proto_rawDesc), len(file_erasurecoding_proto_rawDesc)))
	})
	return file_erasurecoding_proto_rawDescData
}

var file_erasurecoding_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_erasurecoding_proto_goTypes = []any{
	(*SetErasureCodingPolicyRequestProto)(nil),          // 0: hadoop.hdfs.SetErasureCodingPolicyRequestProto
	(*SetErasureCodingPolicyResponseProto)(nil),         // 1: hadoop.hdfs.SetErasureCodingPolicyResponseProto
	(*GetErasureCodingPoliciesRequestProto)(nil),        // 2: hadoop.hdfs.GetErasureCodingPoliciesRequestProto
	(*GetErasureCodingPoliciesResponseProto)(nil),       // 3: hadoop.hdfs.GetErasureCodingPoliciesResponseProto
	(*GetErasureCodingCodecsRequestProto)(nil),          // 4: hadoop.hdfs.GetErasureCodingCodecsRequestProto
	(*GetErasureCodingCodecsResponseProto)(nil),         // 5: hadoop.hdfs.GetErasureCodingCodecsResponseProto
	(*GetErasureCodingPolicyRequestProto)(nil),          // 6: hadoop.hdfs.GetErasureCodingPolicyRequestProto
	(*GetErasureCodingPolicyResponseProto)(nil),         // 7: hadoop.hdfs.GetErasureCodingPolicyResponseProto
	(*AddErasureCodingPoliciesRequestProto)(nil),        // 8: hadoop.hdfs.AddErasureCodingPoliciesRequestProto
	(*AddErasureCodingPoliciesResponseProto)(nil),       // 9: hadoop.hdfs.AddErasureCodingPoliciesResponseProto
	(*RemoveErasureCodingPolicyRequestProto)(nil),       // 10: hadoop.hdfs.RemoveErasureCodingPolicyRequestProto
	(*RemoveErasureCodingPolicyResponseProto)(nil),      // 11: hadoop.hdfs.RemoveErasureCodingPolicyResponseProto
	(*EnableErasureCodingPolicyRequestProto)(nil),       // 12: hadoop.hdfs.EnableErasureCodingPolicyRequestProto
	(*EnableErasureCodingPolicyResponseProto)(nil),      // 13: hadoop.hdfs.EnableErasureCodingPolicyResponseProto
	(*DisableErasureCodingPolicyRequestProto)(nil),      // 14: hadoop.hdfs.DisableErasureCodingPolicyRequestProto
	(*DisableErasureCodingPolicyResponseProto)(nil),     // 15: hadoop.hdfs.DisableErasureCodingPolicyResponseProto
	(*UnsetErasureCodingPolicyRequestProto)(nil),        // 16: hadoop.hdfs.UnsetErasureCodingPolicyRequestProto
	(*UnsetErasureCodingPolicyResponseProto)(nil),       // 17: hadoop.hdfs.UnsetErasureCodingPolicyResponseProto
	(*GetECTopologyResultForPoliciesRequestProto)(nil),  // 18: hadoop.hdfs.GetECTopologyResultForPoliciesRequestProto
	(*GetECTopologyResultForPoliciesResponseProto)(nil), // 19: hadoop.hdfs.GetECTopologyResultForPoliciesResponseProto
	(*BlockECReconstructionInfoProto)(nil),              // 20: hadoop.hdfs.BlockECReconstructionInfoProto
	(*CodecProto)(nil),                                  // 21: hadoop.hdfs.CodecProto
	(*ErasureCodingPolicyProto)(nil),                    // 22: hadoop.hdfs.ErasureCodingPolicyProto
	(*AddErasureCodingPolicyResponseProto)(nil),         // 23: hadoop.hdfs.AddErasureCodingPolicyResponseProto
	(*ECTopologyVerifierResultProto)(nil),               // 24: hadoop.hdfs.ECTopologyVerifierResultProto
	(*ExtendedBlockProto)(nil),                          // 25: hadoop.hdfs.ExtendedBlockProto
	(*DatanodeInfosProto)(nil),                          // 26: hadoop.hdfs.DatanodeInfosProto
	(*StorageUuidsProto)(nil),                           // 27: hadoop.hdfs.StorageUuidsProto
	(*StorageTypesProto)(nil),                           // 28: hadoop.hdfs.StorageTypesProto
}
var file_erasurecoding_proto_depIdxs = []int32{
	22, // 0: hadoop.hdfs.GetErasureCodingPoliciesResponseProto.ecPolicies:type_name -> hadoop.hdfs.ErasureCodingPolicyProto
	21, // 1: hadoop.hdfs.GetErasureCodingCodecsResponseProto.codec:type_name -> hadoop.hdfs.CodecProto
	22, // 2: hadoop.hdfs.GetErasureCodingPolicyResponseProto.ecPolicy:type_name -> hadoop.hdfs.ErasureCodingPolicyProto
	22, // 3: hadoop.hdfs.AddErasureCodingPoliciesRequestProto.ecPolicies:type_name -> hadoop.hdfs.ErasureCodingPolicyProto
	23, // 4: hadoop.hdfs.AddErasureCodingPoliciesResponseProto.responses:type_name -> hadoop.hdfs.AddErasureCodingPolicyResponseProto
	24, // 5: hadoop.hdfs.GetECTopologyResultForPoliciesResponseProto.response:type_name -> hadoop.hdfs.ECTopologyVerifierResultProto
	25, // 6: hadoop.hdfs.BlockECReconstructionInfoProto.block:type_name -> hadoop.hdfs.ExtendedBlockProto
	26, // 7: hadoop.hdfs.BlockECReconstructionInfoProto.sourceDnInfos:type_name -> hadoop.hdfs.DatanodeInfosProto
	26, // 8: hadoop.hdfs.BlockECReconstructionInfoProto.targetDnInfos:type_name -> hadoop.hdfs.DatanodeInfosProto
	27, // 9: hadoop.hdfs.BlockECReconstructionInfoProto.targetStorageUuids:type_name -> hadoop.hdfs.StorageUuidsProto
	28, // 10: hadoop.hdfs.BlockECReconstructionInfoProto.targetStorageTypes:type_name -> hadoop.hdfs.StorageTypesProto
	22, // 11: hadoop.hdfs.BlockECReconstructionInfoProto.ecPolicy:type_name -> hadoop.hdfs.ErasureCodingPolicyProto
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_erasurecoding_proto_init() }
func file_erasurecoding_proto_init() {
	if File_erasurecoding_proto != nil {
		return
	}
	file_hdfs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_erasurecoding_proto_rawDesc), len(file_erasurecoding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_erasurecoding_proto_goTypes,
		DependencyIndexes: file_erasurecoding_proto_depIdxs,
		MessageInfos:      file_erasurecoding_proto_msgTypes,
	}.Build()
	File_erasurecoding_proto = out.File
	file_erasurecoding_proto_goTypes = nil
	file_erasurecoding_proto_depIdxs = nil
}
