//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// These .proto interfaces are private and stable.
// Please see http://wiki.apache.org/hadoop/Compatibility
// for what changes are allowed for a *stable* .proto interface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: HAZKInfo.proto

package hadoop_hdfs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActiveNodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameserviceId *string                `protobuf:"bytes,1,req,name=nameserviceId" json:"nameserviceId,omitempty"`
	NamenodeId    *string                `protobuf:"bytes,2,req,name=namenodeId" json:"namenodeId,omitempty"`
	Hostname      *string                `protobuf:"bytes,3,req,name=hostname" json:"hostname,omitempty"`
	Port          *int32                 `protobuf:"varint,4,req,name=port" json:"port,omitempty"`
	ZkfcPort      *int32                 `protobuf:"varint,5,req,name=zkfcPort" json:"zkfcPort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveNodeInfo) Reset() {
	*x = ActiveNodeInfo{}
	mi := &file_HAZKInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveNodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveNodeInfo) ProtoMessage() {}

func (x *ActiveNodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_HAZKInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveNodeInfo.ProtoReflect.Descriptor instead.
func (*ActiveNodeInfo) Descriptor() ([]byte, []int) {
	return file_HAZKInfo_proto_rawDescGZIP(), []int{0}
}

func (x *ActiveNodeInfo) GetNameserviceId() string {
	if x != nil && x.NameserviceId != nil {
		return *x.NameserviceId
	}
	return ""
}

func (x *ActiveNodeInfo) GetNamenodeId() string {
	if x != nil && x.NamenodeId != nil {
		return *x.NamenodeId
	}
	return ""
}

func (x *ActiveNodeInfo) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *ActiveNodeInfo) GetPort() int32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *ActiveNodeInfo) GetZkfcPort() int32 {
	if x != nil && x.ZkfcPort != nil {
		return *x.ZkfcPort
	}
	return 0
}

var File_HAZKInfo_proto protoreflect.FileDescriptor

const file_HAZKInfo_proto_rawDesc = "" +
	"\n" +
	"\x0eHAZKInfo.proto\x12\vhadoop.hdfs\"\xa2\x01\n" +
	"\x0eActiveNodeInfo\x12$\n" +
	"\rnameserviceId\x18\x01 \x02(\tR\rnameserviceId\x12\x1e\n" +
	"\n" +
	"namenodeId\x18\x02 \x02(\tR\n" +
	"namenodeId\x12\x1a\n" +
	"\bhostname\x18\x03 \x02(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x04 \x02(\x05R\x04port\x12\x1a\n" +
	"\bzkfcPort\x18\x05 \x02(\x05R\bzkfcPortB}\n" +
	"/org.apache.hadoop.hdfs.server.namenode.ha.protoB\x0eHAZKInfoProtosZ:github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs"

var (
	file_HAZKInfo_proto_rawDescOnce sync.Once
	file_HAZKInfo_proto_rawDescData []byte
)

func file_HAZKInfo_proto_rawDescGZIP() []byte {
	file_HAZKInfo_proto_rawDescOnce.Do(func() {
		file_HAZKInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_HAZKInfo_proto_rawDesc), len(file_HAZKInfo_proto_rawDesc)))
	})
	return file_HAZKInfo_proto_rawDescData
}

var file_HAZKInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_HAZKInfo_proto_goTypes = []any{
	(*ActiveNodeInfo)(nil), // 0: hadoop.hdfs.ActiveNodeInfo
}
var file_HAZKInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_HAZKInfo_proto_init() }
func file_HAZKInfo_proto_init() {
	if File_HAZKInfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_HAZKInfo_proto_rawDesc), len(file_HAZKInfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_HAZKInfo_proto_goTypes,
		DependencyIndexes: file_HAZKInfo_proto_depIdxs,
		MessageInfos:      file_HAZKInfo_proto_msgTypes,
	}.Build()
	File_HAZKInfo_proto = out.File
	file_HAZKInfo_proto_goTypes = nil
	file_HAZKInfo_proto_depIdxs = nil
}
