//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// These .proto interfaces are private and stable.
// Please see http://wiki.apache.org/hadoop/Compatibility
// for what changes are allowed for a *stable* .proto interface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: inotify.proto

package hadoop_hdfs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_CREATE   EventType = 0
	EventType_EVENT_CLOSE    EventType = 1
	EventType_EVENT_APPEND   EventType = 2
	EventType_EVENT_RENAME   EventType = 3
	EventType_EVENT_METADATA EventType = 4
	EventType_EVENT_UNLINK   EventType = 5
	EventType_EVENT_TRUNCATE EventType = 6
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_CREATE",
		1: "EVENT_CLOSE",
		2: "EVENT_APPEND",
		3: "EVENT_RENAME",
		4: "EVENT_METADATA",
		5: "EVENT_UNLINK",
		6: "EVENT_TRUNCATE",
	}
	EventType_value = map[string]int32{
		"EVENT_CREATE":   0,
		"EVENT_CLOSE":    1,
		"EVENT_APPEND":   2,
		"EVENT_RENAME":   3,
		"EVENT_METADATA": 4,
		"EVENT_UNLINK":   5,
		"EVENT_TRUNCATE": 6,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_inotify_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_inotify_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EventType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EventType(num)
	return nil
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_inotify_proto_rawDescGZIP(), []int{0}
}

type INodeType int32

const (
	INodeType_I_TYPE_FILE      INodeType = 0
	INodeType_I_TYPE_DIRECTORY INodeType = 1
	INodeType_I_TYPE_SYMLINK   INodeType = 2
)

// Enum value maps for INodeType.
var (
	INodeType_name = map[int32]string{
		0: "I_TYPE_FILE",
		1: "I_TYPE_DIRECTORY",
		2: "I_TYPE_SYMLINK",
	}
	INodeType_value = map[string]int32{
		"I_TYPE_FILE":      0,
		"I_TYPE_DIRECTORY": 1,
		"I_TYPE_SYMLINK":   2,
	}
)

func (x INodeType) Enum() *INodeType {
	p := new(INodeType)
	*p = x
	return p
}

func (x INodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (INodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_inotify_proto_enumTypes[1].Descriptor()
}

func (INodeType) Type() protoreflect.EnumType {
	return &file_inotify_proto_enumTypes[1]
}

func (x INodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *INodeType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = INodeType(num)
	return nil
}

// Deprecated: Use INodeType.Descriptor instead.
func (INodeType) EnumDescriptor() ([]byte, []int) {
	return file_inotify_proto_rawDescGZIP(), []int{1}
}

type MetadataUpdateType int32

const (
	MetadataUpdateType_META_TYPE_TIMES       MetadataUpdateType = 0
	MetadataUpdateType_META_TYPE_REPLICATION MetadataUpdateType = 1
	MetadataUpdateType_META_TYPE_OWNER       MetadataUpdateType = 2
	MetadataUpdateType_META_TYPE_PERMS       MetadataUpdateType = 3
	MetadataUpdateType_META_TYPE_ACLS        MetadataUpdateType = 4
	MetadataUpdateType_META_TYPE_XATTRS      MetadataUpdateType = 5
)

// Enum value maps for MetadataUpdateType.
var (
	MetadataUpdateType_name = map[int32]string{
		0: "META_TYPE_TIMES",
		1: "META_TYPE_REPLICATION",
		2: "META_TYPE_OWNER",
		3: "META_TYPE_PERMS",
		4: "META_TYPE_ACLS",
		5: "META_TYPE_XATTRS",
	}
	MetadataUpdateType_value = map[string]int32{
		"META_TYPE_TIMES":       0,
		"META_TYPE_REPLICATION": 1,
		"META_TYPE_OWNER":       2,
		"META_TYPE_PERMS":       3,
		"META_TYPE_ACLS":        4,
		"META_TYPE_XATTRS":      5,
	}
)

func (x MetadataUpdateType) Enum() *MetadataUpdateType {
	p := new(MetadataUpdateType)
	*p = x
	return p
}

func (x MetadataUpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetadataUpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_inotify_proto_enumTypes[2].Descriptor()
}

func (MetadataUpdateType) Type() protoreflect.EnumType {
	return &file_inotify_proto_enumTypes[2]
}

func (x MetadataUpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MetadataUpdateType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MetadataUpdateType(num)
	return nil
}

// Deprecated: Use MetadataUpdateType.Descriptor instead.
func (MetadataUpdateType) EnumDescriptor() ([]byte, []int) {
	return file_inotify_proto_rawDescGZIP(), []int{2}
}

type EventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *EventType             `protobuf:"varint,1,req,name=type,enum=hadoop.hdfs.EventType" json:"type,omitempty"`
	Contents      []byte                 `protobuf:"bytes,2,req,name=contents" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventProto) Reset() {
	*x = EventProto{}
	mi := &file_inotify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventProto) ProtoMessage() {}

func (x *EventProto) ProtoReflect() protoreflect.Message {
	mi := &file_inotify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventProto.ProtoReflect.Descriptor instead.
func (*EventProto) Descriptor() ([]byte, []int) {
	return file_inotify_proto_rawDescGZIP(), []int{0}
}

func (x *EventProto) GetType() EventType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return EventType_EVENT_CREATE
}

func (x *EventProto) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

type EventBatchProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          *int64                 `protobuf:"varint,1,req,name=txid" json:"txid,omitempty"`
	Events        []*EventProto          `protobuf:"bytes,2,rep,name=events" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBatchProto) Reset() {
	*x = EventBatchProto{}
	mi := &file_inotify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatchProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatchProto) ProtoMessage() {}

func (x *EventBatchProto) ProtoReflect() protoreflect.Message {
	mi := &file_inotify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatchProto.ProtoReflect.Descriptor instead.
func (*EventBatchProto) Descriptor() ([]byte, []int) {
	return file_inotify_proto_rawDescGZIP(), []int{1}
}

func (x *EventBatchProto) GetTxid() int64 {
	if x != nil && x.Txid != nil {
		return *x.Txid
	}
	return 0
}

func (x *EventBatchProto) GetEvents() []*EventProto {
	if x != nil {
		return x.Events
	}
	return nil
}

type CreateEventProto struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             *INodeType             `protobuf:"varint,1,req,name=type,enum=hadoop.hdfs.INodeType" json:"type,omitempty"`
	Path             *string                `protobuf:"bytes,2,req,name=path" json:"path,omitempty"`
	Ctime            *int64                 `protobuf:"varint,3,req,name=ctime" json:"ctime,omitempty"`
	OwnerName        *string                `protobuf:"bytes,4,req,name=ownerName" json:"ownerName,omitempty"`
	GroupName        *string                `protobuf:"bytes,5,req,name=groupName" json:"groupName,omitempty"`
	Perms            *FsPermissionProto     `protobuf:"bytes,6,req,name=perms" json:"perms,omitempty"`
	Replication      *int32                 `protobuf:"varint,7,opt,name=replication" json:"replication,omitempty"`
	SymlinkTarget    *string                `protobuf:"bytes,8,opt,name=symlinkTarget" json:"symlinkTarget,omitempty"`
	Overwrite        *bool                  `protobuf:"varint,9,opt,name=overwrite" json:"overwrite,omitempty"`
	DefaultBlockSize *int64                 `protobuf:"varint,10,opt,name=defaultBlockSize,def=0" json:"defaultBlockSize,omitempty"`
	ErasureCoded     *bool                  `protobuf:"varint,11,opt,name=erasureCoded" json:"erasureCoded,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

// Default values for CreateEventProto fields.
const (
	Default_CreateEventProto_DefaultBlockSize = int64(0)
)

func (x *CreateEventProto) Reset() {
	*x = CreateEventProto{}
	mi := &file_inotify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventProto) ProtoMessage() {}

func (x *CreateEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_inotify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventProto.ProtoReflect.Descriptor instead.
func (*CreateEventProto) Descriptor() ([]byte, []int) {
	return file_inotify_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventProto) GetType() INodeType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return INodeType_I_TYPE_FILE
}

func (x *CreateEventProto) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *CreateEventProto) GetCtime() int64 {
	if x != nil && x.Ctime != nil {
		return *x.Ctime
	}
	return 0
}

func (x *CreateEventProto) GetOwnerName() string {
	if x != nil && x.OwnerName != nil {
		return *x.OwnerName
	}
	return ""
}

func (x *CreateEventProto) GetGroupName() string {
	if x != nil && x.GroupName != nil {
		return *x.GroupName
	}
	return ""
}

func (x *CreateEventProto) GetPerms() *FsPermissionProto {
	if x != nil {
		return x.Perms
	}
	return nil
}

func (x *CreateEventProto) GetReplication() int32 {
	if x != nil && x.Replication != nil {
		return *x.Replication
	}
	return 0
}

func (x *CreateEventProto) GetSymlinkTarget() string {
	if x != nil && x.SymlinkTarget != nil {
		return *x.SymlinkTarget
	}
	return ""
}

func (x *CreateEventProto) GetOverwrite() bool {
	if x != nil && x.Overwrite != nil {
		return *x.Overwrite
	}
	return false
}

func (x *CreateEventProto) GetDefaultBlockSize() int64 {
	if x != nil && x.DefaultBlockSize != nil {
		return *x.DefaultBlockSize
	}
	return Default_CreateEventProto_DefaultBlockSize
}

func (x *CreateEventProto) GetErasureCoded() bool {
	if x != nil && x.ErasureCoded != nil {
		return *x.ErasureCoded
	}
	return false
}

type CloseEventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	FileSize      *int64                 `protobuf:"varint,2,req,name=fileSize" json:"fileSize,omitempty"`
	Timestamp     *int64                 `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseEventProto) Reset() {
	*x = CloseEventProto{}
	mi := &file_inotify_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseEventProto) ProtoMessage() {}

func (x *CloseEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_inotify_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseEventProto.ProtoReflect.Descriptor instead.
func (*CloseEventProto) Descriptor() ([]byte, []int) {
	return file_inotify_proto_rawDescGZIP(), []int{3}
}

func (x *CloseEventProto) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *CloseEventProto) GetFileSize() int64 {
	if x != nil && x.FileSize != nil {
		return *x.FileSize
	}
	return 0
}

func (x *CloseEventProto) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

type TruncateEventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	FileSize      *int64                 `protobuf:"varint,2,req,name=fileSize" json:"fileSize,omitempty"`
	Timestamp     *int64                 `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TruncateEventProto) Reset() {
	*x = TruncateEventProto{}
	mi := &file_inotify_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruncateEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruncateEventProto) ProtoMessage() {}

func (x *TruncateEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_inotify_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruncateEventProto.ProtoReflect.Descriptor instead.
func (*TruncateEventProto) Descriptor() ([]byte, []int) {
	return file_inotify_proto_rawDescGZIP(), []int{4}
}

func (x *TruncateEventProto) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *TruncateEventProto) GetFileSize() int64 {
	if x != nil && x.FileSize != nil {
		return *x.FileSize
	}
	return 0
}

func (x *TruncateEventProto) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

type AppendEventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	NewBlock      *bool                  `protobuf:"varint,2,opt,name=newBlock,def=0" json:"newBlock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for AppendEventProto fields.
const (
	Default_AppendEventProto_NewBlock = bool(false)
)

func (x *AppendEventProto) Reset() {
	*x = AppendEventProto{}
	mi := &file_inotify_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEventProto) ProtoMessage() {}

func (x *AppendEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_inotify_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEventProto.ProtoReflect.Descriptor instead.
func (*AppendEventProto) Descriptor() ([]byte, []int) {
	return file_inotify_proto_rawDescGZIP(), []int{5}
}

func (x *AppendEventProto) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *AppendEventProto) GetNewBlock() bool {
	if x != nil && x.NewBlock != nil {
		return *x.NewBlock
	}
	return Default_AppendEventProto_NewBlock
}

type RenameEventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcPath       *string                `protobuf:"bytes,1,req,name=srcPath" json:"srcPath,omitempty"`
	DestPath      *string                `protobuf:"bytes,2,req,name=destPath" json:"destPath,omitempty"`
	Timestamp     *int64                 `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameEventProto) Reset() {
	*x = RenameEventProto{}
	mi := &file_inotify_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameEventProto) ProtoMessage() {}

func (x *RenameEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_inotify_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameEventProto.ProtoReflect.Descriptor instead.
func (*RenameEventProto) Descriptor() ([]byte, []int) {
	return file_inotify_proto_rawDescGZIP(), []int{6}
}

func (x *RenameEventProto) GetSrcPath() string {
	if x != nil && x.SrcPath != nil {
		return *x.SrcPath
	}
	return ""
}

func (x *RenameEventProto) GetDestPath() string {
	if x != nil && x.DestPath != nil {
		return *x.DestPath
	}
	return ""
}

func (x *RenameEventProto) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

type MetadataUpdateEventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Type          *MetadataUpdateType    `protobuf:"varint,2,req,name=type,enum=hadoop.hdfs.MetadataUpdateType" json:"type,omitempty"`
	Mtime         *int64                 `protobuf:"varint,3,opt,name=mtime" json:"mtime,omitempty"`
	Atime         *int64                 `protobuf:"varint,4,opt,name=atime" json:"atime,omitempty"`
	Replication   *int32                 `protobuf:"varint,5,opt,name=replication" json:"replication,omitempty"`
	OwnerName     *string                `protobuf:"bytes,6,opt,name=ownerName" json:"ownerName,omitempty"`
	GroupName     *string                `protobuf:"bytes,7,opt,name=groupName" json:"groupName,omitempty"`
	Perms         *FsPermissionProto     `protobuf:"bytes,8,opt,name=perms" json:"perms,omitempty"`
	Acls          []*AclEntryProto       `protobuf:"bytes,9,rep,name=acls" json:"acls,omitempty"`
	XAttrs        []*XAttrProto          `protobuf:"bytes,10,rep,name=xAttrs" json:"xAttrs,omitempty"`
	XAttrsRemoved *bool                  `protobuf:"varint,11,opt,name=xAttrsRemoved" json:"xAttrsRemoved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataUpdateEventProto) Reset() {
	*x = MetadataUpdateEventProto{}
	mi := &file_inotify_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataUpdateEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataUpdateEventProto) ProtoMessage() {}

func (x *MetadataUpdateEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_inotify_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataUpdateEventProto.ProtoReflect.Descriptor instead.
func (*MetadataUpdateEventProto) Descriptor() ([]byte, []int) {
	return file_inotify_proto_rawDescGZIP(), []int{7}
}

func (x *MetadataUpdateEventProto) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *MetadataUpdateEventProto) GetType() MetadataUpdateType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return MetadataUpdateType_META_TYPE_TIMES
}

func (x *MetadataUpdateEventProto) GetMtime() int64 {
	if x != nil && x.Mtime != nil {
		return *x.Mtime
	}
	return 0
}

func (x *MetadataUpdateEventProto) GetAtime() int64 {
	if x != nil && x.Atime != nil {
		return *x.Atime
	}
	return 0
}

func (x *MetadataUpdateEventProto) GetReplication() int32 {
	if x != nil && x.Replication != nil {
		return *x.Replication
	}
	return 0
}

func (x *MetadataUpdateEventProto) GetOwnerName() string {
	if x != nil && x.OwnerName != nil {
		return *x.OwnerName
	}
	return ""
}

func (x *MetadataUpdateEventProto) GetGroupName() string {
	if x != nil && x.GroupName != nil {
		return *x.GroupName
	}
	return ""
}

func (x *MetadataUpdateEventProto) GetPerms() *FsPermissionProto {
	if x != nil {
		return x.Perms
	}
	return nil
}

func (x *MetadataUpdateEventProto) GetAcls() []*AclEntryProto {
	if x != nil {
		return x.Acls
	}
	return nil
}

func (x *MetadataUpdateEventProto) GetXAttrs() []*XAttrProto {
	if x != nil {
		return x.XAttrs
	}
	return nil
}

func (x *MetadataUpdateEventProto) GetXAttrsRemoved() bool {
	if x != nil && x.XAttrsRemoved != nil {
		return *x.XAttrsRemoved
	}
	return false
}

type UnlinkEventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Timestamp     *int64                 `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkEventProto) Reset() {
	*x = UnlinkEventProto{}
	mi := &file_inotify_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkEventProto) ProtoMessage() {}

func (x *UnlinkEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_inotify_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkEventProto.ProtoReflect.Descriptor instead.
func (*UnlinkEventProto) Descriptor() ([]byte, []int) {
	return file_inotify_proto_rawDescGZIP(), []int{8}
}

func (x *UnlinkEventProto) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *UnlinkEventProto) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

type EventsListProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventProto          `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"` // deprecated
	FirstTxid     *int64                 `protobuf:"varint,2,req,name=firstTxid" json:"firstTxid,omitempty"`
	LastTxid      *int64                 `protobuf:"varint,3,req,name=lastTxid" json:"lastTxid,omitempty"`
	SyncTxid      *int64                 `protobuf:"varint,4,req,name=syncTxid" json:"syncTxid,omitempty"`
	Batch         []*EventBatchProto     `protobuf:"bytes,5,rep,name=batch" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsListProto) Reset() {
	*x = EventsListProto{}
	mi := &file_inotify_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsListProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsListProto) ProtoMessage() {}

func (x *EventsListProto) ProtoReflect() protoreflect.Message {
	mi := &file_inotify_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsListProto.ProtoReflect.Descriptor instead.
func (*EventsListProto) Descriptor() ([]byte, []int) {
	return file_inotify_proto_rawDescGZIP(), []int{9}
}

func (x *EventsListProto) GetEvents() []*EventProto {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventsListProto) GetFirstTxid() int64 {
	if x != nil && x.FirstTxid != nil {
		return *x.FirstTxid
	}
	return 0
}

func (x *EventsListProto) GetLastTxid() int64 {
	if x != nil && x.LastTxid != nil {
		return *x.LastTxid
	}
	return 0
}

func (x *EventsListProto) GetSyncTxid() int64 {
	if x != nil && x.SyncTxid != nil {
		return *x.SyncTxid
	}
	return 0
}

func (x *EventsListProto) GetBatch() []*EventBatchProto {
	if x != nil {
		return x.Batch
	}
	return nil
}

var File_inotify_proto protoreflect.FileDescriptor

const file_inotify_proto_rawDesc = "" +
	"\n" +
	"\rinotify.proto\x12\vhadoop.hdfs\x1a\tacl.proto\x1a\vxattr.proto\"T\n" +
	"\n" +
	"EventProto\x12*\n" +
	"\x04type\x18\x01 \x02(\x0e2\x16.hadoop.hdfs.EventTypeR\x04type\x12\x1a\n" +
	"\bcontents\x18\x02 \x02(\fR\bcontents\"V\n" +
	"\x0fEventBatchProto\x12\x12\n" +
	"\x04txid\x18\x01 \x02(\x03R\x04txid\x12/\n" +
	"\x06events\x18\x02 \x03(\v2\x17.hadoop.hdfs.EventProtoR\x06events\"\x93\x03\n" +
	"\x10CreateEventProto\x12*\n" +
	"\x04type\x18\x01 \x02(\x0e2\x16.hadoop.hdfs.INodeTypeR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x02(\tR\x04path\x12\x14\n" +
	"\x05ctime\x18\x03 \x02(\x03R\x05ctime\x12\x1c\n" +
	"\townerName\x18\x04 \x02(\tR\townerName\x12\x1c\n" +
	"\tgroupName\x18\x05 \x02(\tR\tgroupName\x124\n" +
	"\x05perms\x18\x06 \x02(\v2\x1e.hadoop.hdfs.FsPermissionProtoR\x05perms\x12 \n" +
	"\vreplication\x18\a \x01(\x05R\vreplication\x12$\n" +
	"\rsymlinkTarget\x18\b \x01(\tR\rsymlinkTarget\x12\x1c\n" +
	"\toverwrite\x18\t \x01(\bR\toverwrite\x12-\n" +
	"\x10defaultBlockSize\x18\n" +
	" \x01(\x03:\x010R\x10defaultBlockSize\x12\"\n" +
	"\ferasureCoded\x18\v \x01(\bR\ferasureCoded\"_\n" +
	"\x0fCloseEventProto\x12\x12\n" +
	"\x04path\x18\x01 \x02(\tR\x04path\x12\x1a\n" +
	"\bfileSize\x18\x02 \x02(\x03R\bfileSize\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x02(\x03R\ttimestamp\"b\n" +
	"\x12TruncateEventProto\x12\x12\n" +
	"\x04path\x18\x01 \x02(\tR\x04path\x12\x1a\n" +
	"\bfileSize\x18\x02 \x02(\x03R\bfileSize\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x02(\x03R\ttimestamp\"I\n" +
	"\x10AppendEventProto\x12\x12\n" +
	"\x04path\x18\x01 \x02(\tR\x04path\x12!\n" +
	"\bnewBlock\x18\x02 \x01(\b:\x05falseR\bnewBlock\"f\n" +
	"\x10RenameEventProto\x12\x18\n" +
	"\asrcPath\x18\x01 \x02(\tR\asrcPath\x12\x1a\n" +
	"\bdestPath\x18\x02 \x02(\tR\bdestPath\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x02(\x03R\ttimestamp\"\xaa\x03\n" +
	"\x18MetadataUpdateEventProto\x12\x12\n" +
	"\x04path\x18\x01 \x02(\tR\x04path\x123\n" +
	"\x04type\x18\x02 \x02(\x0e2\x1f.hadoop.hdfs.MetadataUpdateTypeR\x04type\x12\x14\n" +
	"\x05mtime\x18\x03 \x01(\x03R\x05mtime\x12\x14\n" +
	"\x05atime\x18\x04 \x01(\x03R\x05atime\x12 \n" +
	"\vreplication\x18\x05 \x01(\x05R\vreplication\x12\x1c\n" +
	"\townerName\x18\x06 \x01(\tR\townerName\x12\x1c\n" +
	"\tgroupName\x18\a \x01(\tR\tgroupName\x124\n" +
	"\x05perms\x18\b \x01(\v2\x1e.hadoop.hdfs.FsPermissionProtoR\x05perms\x12.\n" +
	"\x04acls\x18\t \x03(\v2\x1a.hadoop.hdfs.AclEntryProtoR\x04acls\x12/\n" +
	"\x06xAttrs\x18\n" +
	" \x03(\v2\x17.hadoop.hdfs.XAttrProtoR\x06xAttrs\x12$\n" +
	"\rxAttrsRemoved\x18\v \x01(\bR\rxAttrsRemoved\"D\n" +
	"\x10UnlinkEventProto\x12\x12\n" +
	"\x04path\x18\x01 \x02(\tR\x04path\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x02(\x03R\ttimestamp\"\xcc\x01\n" +
	"\x0fEventsListProto\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.hadoop.hdfs.EventProtoR\x06events\x12\x1c\n" +
	"\tfirstTxid\x18\x02 \x02(\x03R\tfirstTxid\x12\x1a\n" +
	"\blastTxid\x18\x03 \x02(\x03R\blastTxid\x12\x1a\n" +
	"\bsyncTxid\x18\x04 \x02(\x03R\bsyncTxid\x122\n" +
	"\x05batch\x18\x05 \x03(\v2\x1c.hadoop.hdfs.EventBatchProtoR\x05batch*\x8c\x01\n" +
	"\tEventType\x12\x10\n" +
	"\fEVENT_CREATE\x10\x00\x12\x0f\n" +
	"\vEVENT_CLOSE\x10\x01\x12\x10\n" +
	"\fEVENT_APPEND\x10\x02\x12\x10\n" +
	"\fEVENT_RENAME\x10\x03\x12\x12\n" +
	"\x0eEVENT_METADATA\x10\x04\x12\x10\n" +
	"\fEVENT_UNLINK\x10\x05\x12\x12\n" +
	"\x0eEVENT_TRUNCATE\x10\x06*F\n" +
	"\tINodeType\x12\x0f\n" +
	"\vI_TYPE_FILE\x10\x00\x12\x14\n" +
	"\x10I_TYPE_DIRECTORY\x10\x01\x12\x12\n" +
	"\x0eI_TYPE_SYMLINK\x10\x02*\x98\x01\n" +
	"\x12MetadataUpdateType\x12\x13\n" +
	"\x0fMETA_TYPE_TIMES\x10\x00\x12\x19\n" +
	"\x15META_TYPE_REPLICATION\x10\x01\x12\x13\n" +
	"\x0fMETA_TYPE_OWNER\x10\x02\x12\x13\n" +
	"\x0fMETA_TYPE_PERMS\x10\x03\x12\x12\n" +
	"\x0eMETA_TYPE_ACLS\x10\x04\x12\x14\n" +
	"\x10META_TYPE_XATTRS\x10\x05Bu\n" +
	"%org.apache.hadoop.hdfs.protocol.protoB\rInotifyProtosZ:github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs\xa0\x01\x01"

var (
	file_inotify_proto_rawDescOnce sync.Once
	file_inotify_proto_rawDescData []byte
)

func file_inotify_proto_rawDescGZIP() []byte {
	file_inotify_proto_rawDescOnce.Do(func() {
		file_inotify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inotify_proto_rawDesc), len(file_inotify_proto_rawDesc)))
	})
	return file_inotify_proto_rawDescData
}

var file_inotify_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_inotify_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_inotify_proto_goTypes = []any{
	(EventType)(0),                   // 0: hadoop.hdfs.EventType
	(INodeType)(0),                   // 1: hadoop.hdfs.INodeType
	(MetadataUpdateType)(0),          // 2: hadoop.hdfs.MetadataUpdateType
	(*EventProto)(nil),               // 3: hadoop.hdfs.EventProto
	(*EventBatchProto)(nil),          // 4: hadoop.hdfs.EventBatchProto
	(*CreateEventProto)(nil),         // 5: hadoop.hdfs.CreateEventProto
	(*CloseEventProto)(nil),          // 6: hadoop.hdfs.CloseEventProto
	(*TruncateEventProto)(nil),       // 7: hadoop.hdfs.TruncateEventProto
	(*AppendEventProto)(nil),         // 8: hadoop.hdfs.AppendEventProto
	(*RenameEventProto)(nil),         // 9: hadoop.hdfs.RenameEventProto
	(*MetadataUpdateEventProto)(nil), // 10: hadoop.hdfs.MetadataUpdateEventProto
	(*UnlinkEventProto)(nil),         // 11: hadoop.hdfs.UnlinkEventProto
	(*EventsListProto)(nil),          // 12: hadoop.hdfs.EventsListProto
	(*FsPermissionProto)(nil),        // 13: hadoop.hdfs.FsPermissionProto
	(*AclEntryProto)(nil),            // 14: hadoop.hdfs.AclEntryProto
	(*XAttrProto)(nil),               // 15: hadoop.hdfs.XAttrProto
}
var file_inotify_proto_depIdxs = []int32{
	0,  // 0: hadoop.hdfs.EventProto.type:type_name -> hadoop.hdfs.EventType
	3,  // 1: hadoop.hdfs.EventBatchProto.events:type_name -> hadoop.hdfs.EventProto
	1,  // 2: hadoop.hdfs.CreateEventProto.type:type_name -> hadoop.hdfs.INodeType
	13, // 3: hadoop.hdfs.CreateEventProto.perms:type_name -> hadoop.hdfs.FsPermissionProto
	2,  // 4: hadoop.hdfs.MetadataUpdateEventProto.type:type_name -> hadoop.hdfs.MetadataUpdateType
	13, // 5: hadoop.hdfs.MetadataUpdateEventProto.perms:type_name -> hadoop.hdfs.FsPermissionProto
	14, // 6: hadoop.hdfs.MetadataUpdateEventProto.acls:type_name -> hadoop.hdfs.AclEntryProto
	15, // 7: hadoop.hdfs.MetadataUpdateEventProto.xAttrs:type_name -> hadoop.hdfs.XAttrProto
	3,  // 8: hadoop.hdfs.EventsListProto.events:type_name -> hadoop.hdfs.EventProto
	4,  // 9: hadoop.hdfs.EventsListProto.batch:type_name -> hadoop.hdfs.EventBatchProto
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_inotify_proto_init() }
func file_inotify_proto_init() {
	if File_inotify_proto != nil {
		return
	}
	file_acl_proto_init()
	file_xattr_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inotify_proto_rawDesc), len(file_inotify_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inotify_proto_goTypes,
		DependencyIndexes: file_inotify_proto_depIdxs,
		EnumInfos:         file_inotify_proto_enumTypes,
		MessageInfos:      file_inotify_proto_msgTypes,
	}.Build()
	File_inotify_proto = out.File
	file_inotify_proto_goTypes = nil
	file_inotify_proto_depIdxs = nil
}
