//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// These .proto interfaces are private and stable.
// Please see http://wiki.apache.org/hadoop/Compatibility
// for what changes are allowed for a *stable* .proto interface.

// This file contains protocol buffers that are used throughout HDFS -- i.e.
// by the client, server, and data transfer protocols.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: InterDatanodeProtocol.proto

package hadoop_hdfs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Block with location information and new generation stamp
// to be used for recovery.
type InitReplicaRecoveryRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *RecoveringBlockProto  `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitReplicaRecoveryRequestProto) Reset() {
	*x = InitReplicaRecoveryRequestProto{}
	mi := &file_InterDatanodeProtocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitReplicaRecoveryRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitReplicaRecoveryRequestProto) ProtoMessage() {}

func (x *InitReplicaRecoveryRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_InterDatanodeProtocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitReplicaRecoveryRequestProto.ProtoReflect.Descriptor instead.
func (*InitReplicaRecoveryRequestProto) Descriptor() ([]byte, []int) {
	return file_InterDatanodeProtocol_proto_rawDescGZIP(), []int{0}
}

func (x *InitReplicaRecoveryRequestProto) GetBlock() *RecoveringBlockProto {
	if x != nil {
		return x.Block
	}
	return nil
}

// *
// Repica recovery information
type InitReplicaRecoveryResponseProto struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ReplicaFound *bool                  `protobuf:"varint,1,req,name=replicaFound" json:"replicaFound,omitempty"`
	// The following entries are not set if there was no replica found.
	State         *ReplicaStateProto `protobuf:"varint,2,opt,name=state,enum=hadoop.hdfs.ReplicaStateProto" json:"state,omitempty"` // State of the replica
	Block         *BlockProto        `protobuf:"bytes,3,opt,name=block" json:"block,omitempty"`                                     // block information
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitReplicaRecoveryResponseProto) Reset() {
	*x = InitReplicaRecoveryResponseProto{}
	mi := &file_InterDatanodeProtocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitReplicaRecoveryResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitReplicaRecoveryResponseProto) ProtoMessage() {}

func (x *InitReplicaRecoveryResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_InterDatanodeProtocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitReplicaRecoveryResponseProto.ProtoReflect.Descriptor instead.
func (*InitReplicaRecoveryResponseProto) Descriptor() ([]byte, []int) {
	return file_InterDatanodeProtocol_proto_rawDescGZIP(), []int{1}
}

func (x *InitReplicaRecoveryResponseProto) GetReplicaFound() bool {
	if x != nil && x.ReplicaFound != nil {
		return *x.ReplicaFound
	}
	return false
}

func (x *InitReplicaRecoveryResponseProto) GetState() ReplicaStateProto {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ReplicaStateProto_FINALIZED
}

func (x *InitReplicaRecoveryResponseProto) GetBlock() *BlockProto {
	if x != nil {
		return x.Block
	}
	return nil
}

// *
// Update replica with new generation stamp and length
type UpdateReplicaUnderRecoveryRequestProto struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Block      *ExtendedBlockProto    `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`            // Block identifier
	RecoveryId *uint64                `protobuf:"varint,2,req,name=recoveryId" json:"recoveryId,omitempty"` // New genstamp of the replica
	NewLength  *uint64                `protobuf:"varint,3,req,name=newLength" json:"newLength,omitempty"`   // New length of the replica
	// New blockId for copy (truncate), default is 0.
	NewBlockId    *uint64 `protobuf:"varint,4,opt,name=newBlockId,def=0" json:"newBlockId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for UpdateReplicaUnderRecoveryRequestProto fields.
const (
	Default_UpdateReplicaUnderRecoveryRequestProto_NewBlockId = uint64(0)
)

func (x *UpdateReplicaUnderRecoveryRequestProto) Reset() {
	*x = UpdateReplicaUnderRecoveryRequestProto{}
	mi := &file_InterDatanodeProtocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReplicaUnderRecoveryRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplicaUnderRecoveryRequestProto) ProtoMessage() {}

func (x *UpdateReplicaUnderRecoveryRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_InterDatanodeProtocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplicaUnderRecoveryRequestProto.ProtoReflect.Descriptor instead.
func (*UpdateReplicaUnderRecoveryRequestProto) Descriptor() ([]byte, []int) {
	return file_InterDatanodeProtocol_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateReplicaUnderRecoveryRequestProto) GetBlock() *ExtendedBlockProto {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *UpdateReplicaUnderRecoveryRequestProto) GetRecoveryId() uint64 {
	if x != nil && x.RecoveryId != nil {
		return *x.RecoveryId
	}
	return 0
}

func (x *UpdateReplicaUnderRecoveryRequestProto) GetNewLength() uint64 {
	if x != nil && x.NewLength != nil {
		return *x.NewLength
	}
	return 0
}

func (x *UpdateReplicaUnderRecoveryRequestProto) GetNewBlockId() uint64 {
	if x != nil && x.NewBlockId != nil {
		return *x.NewBlockId
	}
	return Default_UpdateReplicaUnderRecoveryRequestProto_NewBlockId
}

// *
// Response returns updated block information
type UpdateReplicaUnderRecoveryResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StorageUuid   *string                `protobuf:"bytes,1,opt,name=storageUuid" json:"storageUuid,omitempty"` // ID of the storage that stores replica
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReplicaUnderRecoveryResponseProto) Reset() {
	*x = UpdateReplicaUnderRecoveryResponseProto{}
	mi := &file_InterDatanodeProtocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReplicaUnderRecoveryResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplicaUnderRecoveryResponseProto) ProtoMessage() {}

func (x *UpdateReplicaUnderRecoveryResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_InterDatanodeProtocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplicaUnderRecoveryResponseProto.ProtoReflect.Descriptor instead.
func (*UpdateReplicaUnderRecoveryResponseProto) Descriptor() ([]byte, []int) {
	return file_InterDatanodeProtocol_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateReplicaUnderRecoveryResponseProto) GetStorageUuid() string {
	if x != nil && x.StorageUuid != nil {
		return *x.StorageUuid
	}
	return ""
}

var File_InterDatanodeProtocol_proto protoreflect.FileDescriptor

const file_InterDatanodeProtocol_proto_rawDesc = "" +
	"\n" +
	"\x1bInterDatanodeProtocol.proto\x12\vhadoop.hdfs\x1a\n" +
	"hdfs.proto\x1a\x10HdfsServer.proto\"Z\n" +
	"\x1fInitReplicaRecoveryRequestProto\x127\n" +
	"\x05block\x18\x01 \x02(\v2!.hadoop.hdfs.RecoveringBlockProtoR\x05block\"\xab\x01\n" +
	" InitReplicaRecoveryResponseProto\x12\"\n" +
	"\freplicaFound\x18\x01 \x02(\bR\freplicaFound\x124\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1e.hadoop.hdfs.ReplicaStateProtoR\x05state\x12-\n" +
	"\x05block\x18\x03 \x01(\v2\x17.hadoop.hdfs.BlockProtoR\x05block\"\xc0\x01\n" +
	"&UpdateReplicaUnderRecoveryRequestProto\x125\n" +
	"\x05block\x18\x01 \x02(\v2\x1f.hadoop.hdfs.ExtendedBlockProtoR\x05block\x12\x1e\n" +
	"\n" +
	"recoveryId\x18\x02 \x02(\x04R\n" +
	"recoveryId\x12\x1c\n" +
	"\tnewLength\x18\x03 \x02(\x04R\tnewLength\x12!\n" +
	"\n" +
	"newBlockId\x18\x04 \x01(\x04:\x010R\n" +
	"newBlockId\"K\n" +
	"'UpdateReplicaUnderRecoveryResponseProto\x12 \n" +
	"\vstorageUuid\x18\x01 \x01(\tR\vstorageUuid2\x9c\x02\n" +
	"\x1cInterDatanodeProtocolService\x12r\n" +
	"\x13initReplicaRecovery\x12,.hadoop.hdfs.InitReplicaRecoveryRequestProto\x1a-.hadoop.hdfs.InitReplicaRecoveryResponseProto\x12\x87\x01\n" +
	"\x1aupdateReplicaUnderRecovery\x123.hadoop.hdfs.UpdateReplicaUnderRecoveryRequestProto\x1a4.hadoop.hdfs.UpdateReplicaUnderRecoveryResponseProtoB\x86\x01\n" +
	"%org.apache.hadoop.hdfs.protocol.protoB\x1bInterDatanodeProtocolProtosZ:github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs\x88\x01\x01\xa0\x01\x01"

var (
	file_InterDatanodeProtocol_proto_rawDescOnce sync.Once
	file_InterDatanodeProtocol_proto_rawDescData []byte
)

func file_InterDatanodeProtocol_proto_rawDescGZIP() []byte {
	file_InterDatanodeProtocol_proto_rawDescOnce.Do(func() {
		file_InterDatanodeProtocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_InterDatanodeProtocol_proto_rawDesc), len(file_InterDatanodeProtocol_proto_rawDesc)))
	})
	return file_InterDatanodeProtocol_proto_rawDescData
}

var file_InterDatanodeProtocol_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_InterDatanodeProtocol_proto_goTypes = []any{
	(*InitReplicaRecoveryRequestProto)(nil),         // 0: hadoop.hdfs.InitReplicaRecoveryRequestProto
	(*InitReplicaRecoveryResponseProto)(nil),        // 1: hadoop.hdfs.InitReplicaRecoveryResponseProto
	(*UpdateReplicaUnderRecoveryRequestProto)(nil),  // 2: hadoop.hdfs.UpdateReplicaUnderRecoveryRequestProto
	(*UpdateReplicaUnderRecoveryResponseProto)(nil), // 3: hadoop.hdfs.UpdateReplicaUnderRecoveryResponseProto
	(*RecoveringBlockProto)(nil),                    // 4: hadoop.hdfs.RecoveringBlockProto
	(ReplicaStateProto)(0),                          // 5: hadoop.hdfs.ReplicaStateProto
	(*BlockProto)(nil),                              // 6: hadoop.hdfs.BlockProto
	(*ExtendedBlockProto)(nil),                      // 7: hadoop.hdfs.ExtendedBlockProto
}
var file_InterDatanodeProtocol_proto_depIdxs = []int32{
	4, // 0: hadoop.hdfs.InitReplicaRecoveryRequestProto.block:type_name -> hadoop.hdfs.RecoveringBlockProto
	5, // 1: hadoop.hdfs.InitReplicaRecoveryResponseProto.state:type_name -> hadoop.hdfs.ReplicaStateProto
	6, // 2: hadoop.hdfs.InitReplicaRecoveryResponseProto.block:type_name -> hadoop.hdfs.BlockProto
	7, // 3: hadoop.hdfs.UpdateReplicaUnderRecoveryRequestProto.block:type_name -> hadoop.hdfs.ExtendedBlockProto
	0, // 4: hadoop.hdfs.InterDatanodeProtocolService.initReplicaRecovery:input_type -> hadoop.hdfs.InitReplicaRecoveryRequestProto
	2, // 5: hadoop.hdfs.InterDatanodeProtocolService.updateReplicaUnderRecovery:input_type -> hadoop.hdfs.UpdateReplicaUnderRecoveryRequestProto
	1, // 6: hadoop.hdfs.InterDatanodeProtocolService.initReplicaRecovery:output_type -> hadoop.hdfs.InitReplicaRecoveryResponseProto
	3, // 7: hadoop.hdfs.InterDatanodeProtocolService.updateReplicaUnderRecovery:output_type -> hadoop.hdfs.UpdateReplicaUnderRecoveryResponseProto
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_InterDatanodeProtocol_proto_init() }
func file_InterDatanodeProtocol_proto_init() {
	if File_InterDatanodeProtocol_proto != nil {
		return
	}
	file_hdfs_proto_init()
	file_HdfsServer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_InterDatanodeProtocol_proto_rawDesc), len(file_InterDatanodeProtocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_InterDatanodeProtocol_proto_goTypes,
		DependencyIndexes: file_InterDatanodeProtocol_proto_depIdxs,
		MessageInfos:      file_InterDatanodeProtocol_proto_msgTypes,
	}.Build()
	File_InterDatanodeProtocol_proto = out.File
	file_InterDatanodeProtocol_proto_goTypes = nil
	file_InterDatanodeProtocol_proto_depIdxs = nil
}
