//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: ReconfigurationProtocol.proto

package hadoop_hdfs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// * Asks NN/DN to reload configuration file.
type StartReconfigurationRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartReconfigurationRequestProto) Reset() {
	*x = StartReconfigurationRequestProto{}
	mi := &file_ReconfigurationProtocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartReconfigurationRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReconfigurationRequestProto) ProtoMessage() {}

func (x *StartReconfigurationRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_ReconfigurationProtocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReconfigurationRequestProto.ProtoReflect.Descriptor instead.
func (*StartReconfigurationRequestProto) Descriptor() ([]byte, []int) {
	return file_ReconfigurationProtocol_proto_rawDescGZIP(), []int{0}
}

type StartReconfigurationResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartReconfigurationResponseProto) Reset() {
	*x = StartReconfigurationResponseProto{}
	mi := &file_ReconfigurationProtocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartReconfigurationResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReconfigurationResponseProto) ProtoMessage() {}

func (x *StartReconfigurationResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_ReconfigurationProtocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReconfigurationResponseProto.ProtoReflect.Descriptor instead.
func (*StartReconfigurationResponseProto) Descriptor() ([]byte, []int) {
	return file_ReconfigurationProtocol_proto_rawDescGZIP(), []int{1}
}

// * Query the running status of reconfiguration process
type GetReconfigurationStatusRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReconfigurationStatusRequestProto) Reset() {
	*x = GetReconfigurationStatusRequestProto{}
	mi := &file_ReconfigurationProtocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReconfigurationStatusRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReconfigurationStatusRequestProto) ProtoMessage() {}

func (x *GetReconfigurationStatusRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_ReconfigurationProtocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReconfigurationStatusRequestProto.ProtoReflect.Descriptor instead.
func (*GetReconfigurationStatusRequestProto) Descriptor() ([]byte, []int) {
	return file_ReconfigurationProtocol_proto_rawDescGZIP(), []int{2}
}

type GetReconfigurationStatusConfigChangeProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	OldValue      *string                `protobuf:"bytes,2,req,name=oldValue" json:"oldValue,omitempty"`
	NewValue      *string                `protobuf:"bytes,3,opt,name=newValue" json:"newValue,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,4,opt,name=errorMessage" json:"errorMessage,omitempty"` // It is empty if success.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReconfigurationStatusConfigChangeProto) Reset() {
	*x = GetReconfigurationStatusConfigChangeProto{}
	mi := &file_ReconfigurationProtocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReconfigurationStatusConfigChangeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReconfigurationStatusConfigChangeProto) ProtoMessage() {}

func (x *GetReconfigurationStatusConfigChangeProto) ProtoReflect() protoreflect.Message {
	mi := &file_ReconfigurationProtocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReconfigurationStatusConfigChangeProto.ProtoReflect.Descriptor instead.
func (*GetReconfigurationStatusConfigChangeProto) Descriptor() ([]byte, []int) {
	return file_ReconfigurationProtocol_proto_rawDescGZIP(), []int{3}
}

func (x *GetReconfigurationStatusConfigChangeProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GetReconfigurationStatusConfigChangeProto) GetOldValue() string {
	if x != nil && x.OldValue != nil {
		return *x.OldValue
	}
	return ""
}

func (x *GetReconfigurationStatusConfigChangeProto) GetNewValue() string {
	if x != nil && x.NewValue != nil {
		return *x.NewValue
	}
	return ""
}

func (x *GetReconfigurationStatusConfigChangeProto) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type GetReconfigurationStatusResponseProto struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	StartTime     *int64                                       `protobuf:"varint,1,req,name=startTime" json:"startTime,omitempty"`
	EndTime       *int64                                       `protobuf:"varint,2,opt,name=endTime" json:"endTime,omitempty"`
	Changes       []*GetReconfigurationStatusConfigChangeProto `protobuf:"bytes,3,rep,name=changes" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReconfigurationStatusResponseProto) Reset() {
	*x = GetReconfigurationStatusResponseProto{}
	mi := &file_ReconfigurationProtocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReconfigurationStatusResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReconfigurationStatusResponseProto) ProtoMessage() {}

func (x *GetReconfigurationStatusResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_ReconfigurationProtocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReconfigurationStatusResponseProto.ProtoReflect.Descriptor instead.
func (*GetReconfigurationStatusResponseProto) Descriptor() ([]byte, []int) {
	return file_ReconfigurationProtocol_proto_rawDescGZIP(), []int{4}
}

func (x *GetReconfigurationStatusResponseProto) GetStartTime() int64 {
	if x != nil && x.StartTime != nil {
		return *x.StartTime
	}
	return 0
}

func (x *GetReconfigurationStatusResponseProto) GetEndTime() int64 {
	if x != nil && x.EndTime != nil {
		return *x.EndTime
	}
	return 0
}

func (x *GetReconfigurationStatusResponseProto) GetChanges() []*GetReconfigurationStatusConfigChangeProto {
	if x != nil {
		return x.Changes
	}
	return nil
}

// * Query the reconfigurable properties on NN/DN.
type ListReconfigurablePropertiesRequestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReconfigurablePropertiesRequestProto) Reset() {
	*x = ListReconfigurablePropertiesRequestProto{}
	mi := &file_ReconfigurationProtocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReconfigurablePropertiesRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReconfigurablePropertiesRequestProto) ProtoMessage() {}

func (x *ListReconfigurablePropertiesRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_ReconfigurationProtocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReconfigurablePropertiesRequestProto.ProtoReflect.Descriptor instead.
func (*ListReconfigurablePropertiesRequestProto) Descriptor() ([]byte, []int) {
	return file_ReconfigurationProtocol_proto_rawDescGZIP(), []int{5}
}

type ListReconfigurablePropertiesResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          []string               `protobuf:"bytes,1,rep,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReconfigurablePropertiesResponseProto) Reset() {
	*x = ListReconfigurablePropertiesResponseProto{}
	mi := &file_ReconfigurationProtocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReconfigurablePropertiesResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReconfigurablePropertiesResponseProto) ProtoMessage() {}

func (x *ListReconfigurablePropertiesResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_ReconfigurationProtocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReconfigurablePropertiesResponseProto.ProtoReflect.Descriptor instead.
func (*ListReconfigurablePropertiesResponseProto) Descriptor() ([]byte, []int) {
	return file_ReconfigurationProtocol_proto_rawDescGZIP(), []int{6}
}

func (x *ListReconfigurablePropertiesResponseProto) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

var File_ReconfigurationProtocol_proto protoreflect.FileDescriptor

const file_ReconfigurationProtocol_proto_rawDesc = "" +
	"\n" +
	"\x1dReconfigurationProtocol.proto\x12\vhadoop.hdfs\"\"\n" +
	" StartReconfigurationRequestProto\"#\n" +
	"!StartReconfigurationResponseProto\"&\n" +
	"$GetReconfigurationStatusRequestProto\"\x9b\x01\n" +
	")GetReconfigurationStatusConfigChangeProto\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x12\x1a\n" +
	"\boldValue\x18\x02 \x02(\tR\boldValue\x12\x1a\n" +
	"\bnewValue\x18\x03 \x01(\tR\bnewValue\x12\"\n" +
	"\ferrorMessage\x18\x04 \x01(\tR\ferrorMessage\"\xb1\x01\n" +
	"%GetReconfigurationStatusResponseProto\x12\x1c\n" +
	"\tstartTime\x18\x01 \x02(\x03R\tstartTime\x12\x18\n" +
	"\aendTime\x18\x02 \x01(\x03R\aendTime\x12P\n" +
	"\achanges\x18\x03 \x03(\v26.hadoop.hdfs.GetReconfigurationStatusConfigChangeProtoR\achanges\"*\n" +
	"(ListReconfigurablePropertiesRequestProto\"?\n" +
	")ListReconfigurablePropertiesResponseProto\x12\x12\n" +
	"\x04name\x18\x01 \x03(\tR\x04name2\xab\x03\n" +
	"\x1eReconfigurationProtocolService\x12\x81\x01\n" +
	"\x18getReconfigurationStatus\x121.hadoop.hdfs.GetReconfigurationStatusRequestProto\x1a2.hadoop.hdfs.GetReconfigurationStatusResponseProto\x12u\n" +
	"\x14startReconfiguration\x12-.hadoop.hdfs.StartReconfigurationRequestProto\x1a..hadoop.hdfs.StartReconfigurationResponseProto\x12\x8d\x01\n" +
	"\x1clistReconfigurableProperties\x125.hadoop.hdfs.ListReconfigurablePropertiesRequestProto\x1a6.hadoop.hdfs.ListReconfigurablePropertiesResponseProtoB\x88\x01\n" +
	"%org.apache.hadoop.hdfs.protocol.protoB\x1dReconfigurationProtocolProtosZ:github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs\x88\x01\x01\xa0\x01\x01"

var (
	file_ReconfigurationProtocol_proto_rawDescOnce sync.Once
	file_ReconfigurationProtocol_proto_rawDescData []byte
)

func file_ReconfigurationProtocol_proto_rawDescGZIP() []byte {
	file_ReconfigurationProtocol_proto_rawDescOnce.Do(func() {
		file_ReconfigurationProtocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ReconfigurationProtocol_proto_rawDesc), len(file_ReconfigurationProtocol_proto_rawDesc)))
	})
	return file_ReconfigurationProtocol_proto_rawDescData
}

var file_ReconfigurationProtocol_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ReconfigurationProtocol_proto_goTypes = []any{
	(*StartReconfigurationRequestProto)(nil),          // 0: hadoop.hdfs.StartReconfigurationRequestProto
	(*StartReconfigurationResponseProto)(nil),         // 1: hadoop.hdfs.StartReconfigurationResponseProto
	(*GetReconfigurationStatusRequestProto)(nil),      // 2: hadoop.hdfs.GetReconfigurationStatusRequestProto
	(*GetReconfigurationStatusConfigChangeProto)(nil), // 3: hadoop.hdfs.GetReconfigurationStatusConfigChangeProto
	(*GetReconfigurationStatusResponseProto)(nil),     // 4: hadoop.hdfs.GetReconfigurationStatusResponseProto
	(*ListReconfigurablePropertiesRequestProto)(nil),  // 5: hadoop.hdfs.ListReconfigurablePropertiesRequestProto
	(*ListReconfigurablePropertiesResponseProto)(nil), // 6: hadoop.hdfs.ListReconfigurablePropertiesResponseProto
}
var file_ReconfigurationProtocol_proto_depIdxs = []int32{
	3, // 0: hadoop.hdfs.GetReconfigurationStatusResponseProto.changes:type_name -> hadoop.hdfs.GetReconfigurationStatusConfigChangeProto
	2, // 1: hadoop.hdfs.ReconfigurationProtocolService.getReconfigurationStatus:input_type -> hadoop.hdfs.GetReconfigurationStatusRequestProto
	0, // 2: hadoop.hdfs.ReconfigurationProtocolService.startReconfiguration:input_type -> hadoop.hdfs.StartReconfigurationRequestProto
	5, // 3: hadoop.hdfs.ReconfigurationProtocolService.listReconfigurableProperties:input_type -> hadoop.hdfs.ListReconfigurablePropertiesRequestProto
	4, // 4: hadoop.hdfs.ReconfigurationProtocolService.getReconfigurationStatus:output_type -> hadoop.hdfs.GetReconfigurationStatusResponseProto
	1, // 5: hadoop.hdfs.ReconfigurationProtocolService.startReconfiguration:output_type -> hadoop.hdfs.StartReconfigurationResponseProto
	6, // 6: hadoop.hdfs.ReconfigurationProtocolService.listReconfigurableProperties:output_type -> hadoop.hdfs.ListReconfigurablePropertiesResponseProto
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ReconfigurationProtocol_proto_init() }
func file_ReconfigurationProtocol_proto_init() {
	if File_ReconfigurationProtocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ReconfigurationProtocol_proto_rawDesc), len(file_ReconfigurationProtocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ReconfigurationProtocol_proto_goTypes,
		DependencyIndexes: file_ReconfigurationProtocol_proto_depIdxs,
		MessageInfos:      file_ReconfigurationProtocol_proto_msgTypes,
	}.Build()
	File_ReconfigurationProtocol_proto = out.File
	file_ReconfigurationProtocol_proto_goTypes = nil
	file_ReconfigurationProtocol_proto_depIdxs = nil
}
